// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0-devel
// 	protoc        v3.11.4
// source: typemd.proto

package engine

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// These need to match the values in maho/sql/datatype.go
type DataType int32

const (
	DataType_Unknown DataType = 0
	DataType_Boolean DataType = 1
	DataType_String  DataType = 2
	DataType_Bytes   DataType = 3
	DataType_Float   DataType = 4
	DataType_Integer DataType = 5
)

// Enum value maps for DataType.
var (
	DataType_name = map[int32]string{
		0: "Unknown",
		1: "Boolean",
		2: "String",
		3: "Bytes",
		4: "Float",
		5: "Integer",
	}
	DataType_value = map[string]int32{
		"Unknown": 0,
		"Boolean": 1,
		"String":  2,
		"Bytes":   3,
		"Float":   4,
		"Integer": 5,
	}
)

func (x DataType) Enum() *DataType {
	p := new(DataType)
	*p = x
	return p
}

func (x DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_typemd_proto_enumTypes[0].Descriptor()
}

func (DataType) Type() protoreflect.EnumType {
	return &file_typemd_proto_enumTypes[0]
}

func (x DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataType.Descriptor instead.
func (DataType) EnumDescriptor() ([]byte, []int) {
	return file_typemd_proto_rawDescGZIP(), []int{0}
}

// These need to match the values in maho/sql/constraint.go
type ConstraintType int32

const (
	ConstraintType_UnknownConstraint ConstraintType = 0
	ConstraintType_Default           ConstraintType = 1
	ConstraintType_NotNull           ConstraintType = 2
	ConstraintType_Primary           ConstraintType = 3
	ConstraintType_Unique            ConstraintType = 4
	ConstraintType_Check             ConstraintType = 5
	ConstraintType_Foreign           ConstraintType = 6
)

// Enum value maps for ConstraintType.
var (
	ConstraintType_name = map[int32]string{
		0: "UnknownConstraint",
		1: "Default",
		2: "NotNull",
		3: "Primary",
		4: "Unique",
		5: "Check",
		6: "Foreign",
	}
	ConstraintType_value = map[string]int32{
		"UnknownConstraint": 0,
		"Default":           1,
		"NotNull":           2,
		"Primary":           3,
		"Unique":            4,
		"Check":             5,
		"Foreign":           6,
	}
)

func (x ConstraintType) Enum() *ConstraintType {
	p := new(ConstraintType)
	*p = x
	return p
}

func (x ConstraintType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConstraintType) Descriptor() protoreflect.EnumDescriptor {
	return file_typemd_proto_enumTypes[1].Descriptor()
}

func (ConstraintType) Type() protoreflect.EnumType {
	return &file_typemd_proto_enumTypes[1]
}

func (x ConstraintType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConstraintType.Descriptor instead.
func (ConstraintType) EnumDescriptor() ([]byte, []int) {
	return file_typemd_proto_rawDescGZIP(), []int{1}
}

type TableTypeMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version     int64                 `protobuf:"varint,1,opt,name=Version,proto3" json:"Version,omitempty"`
	Columns     []*ColumnMetadata     `protobuf:"bytes,2,rep,name=Columns,proto3" json:"Columns,omitempty"`
	Primary     []*ColumnKey          `protobuf:"bytes,3,rep,name=Primary,proto3" json:"Primary,omitempty"`
	Indexes     []*IndexMetadata      `protobuf:"bytes,4,rep,name=Indexes,proto3" json:"Indexes,omitempty"`
	Constraints []*ConstraintMetadata `protobuf:"bytes,5,rep,name=Constraints,proto3" json:"Constraints,omitempty"`
	Checks      []*CheckConstraint    `protobuf:"bytes,6,rep,name=Checks,proto3" json:"Checks,omitempty"`
	ForeignKeys []*ForeignKey         `protobuf:"bytes,7,rep,name=ForeignKeys,proto3" json:"ForeignKeys,omitempty"`
	Triggers    []*TriggerMetadata    `protobuf:"bytes,8,rep,name=Triggers,proto3" json:"Triggers,omitempty"`
}

func (x *TableTypeMetadata) Reset() {
	*x = TableTypeMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_typemd_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TableTypeMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableTypeMetadata) ProtoMessage() {}

func (x *TableTypeMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_typemd_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableTypeMetadata.ProtoReflect.Descriptor instead.
func (*TableTypeMetadata) Descriptor() ([]byte, []int) {
	return file_typemd_proto_rawDescGZIP(), []int{0}
}

func (x *TableTypeMetadata) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *TableTypeMetadata) GetColumns() []*ColumnMetadata {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *TableTypeMetadata) GetPrimary() []*ColumnKey {
	if x != nil {
		return x.Primary
	}
	return nil
}

func (x *TableTypeMetadata) GetIndexes() []*IndexMetadata {
	if x != nil {
		return x.Indexes
	}
	return nil
}

func (x *TableTypeMetadata) GetConstraints() []*ConstraintMetadata {
	if x != nil {
		return x.Constraints
	}
	return nil
}

func (x *TableTypeMetadata) GetChecks() []*CheckConstraint {
	if x != nil {
		return x.Checks
	}
	return nil
}

func (x *TableTypeMetadata) GetForeignKeys() []*ForeignKey {
	if x != nil {
		return x.ForeignKeys
	}
	return nil
}

func (x *TableTypeMetadata) GetTriggers() []*TriggerMetadata {
	if x != nil {
		return x.Triggers
	}
	return nil
}

type ColumnMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Type        DataType `protobuf:"varint,2,opt,name=Type,proto3,enum=DataType" json:"Type,omitempty"`
	Size        uint32   `protobuf:"varint,3,opt,name=Size,proto3" json:"Size,omitempty"`
	Fixed       bool     `protobuf:"varint,4,opt,name=Fixed,proto3" json:"Fixed,omitempty"`
	NotNull     bool     `protobuf:"varint,5,opt,name=NotNull,proto3" json:"NotNull,omitempty"`
	Default     []byte   `protobuf:"bytes,6,opt,name=Default,proto3" json:"Default,omitempty"`
	DefaultExpr string   `protobuf:"bytes,7,opt,name=DefaultExpr,proto3" json:"DefaultExpr,omitempty"`
}

func (x *ColumnMetadata) Reset() {
	*x = ColumnMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_typemd_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ColumnMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnMetadata) ProtoMessage() {}

func (x *ColumnMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_typemd_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnMetadata.ProtoReflect.Descriptor instead.
func (*ColumnMetadata) Descriptor() ([]byte, []int) {
	return file_typemd_proto_rawDescGZIP(), []int{1}
}

func (x *ColumnMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ColumnMetadata) GetType() DataType {
	if x != nil {
		return x.Type
	}
	return DataType_Unknown
}

func (x *ColumnMetadata) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ColumnMetadata) GetFixed() bool {
	if x != nil {
		return x.Fixed
	}
	return false
}

func (x *ColumnMetadata) GetNotNull() bool {
	if x != nil {
		return x.NotNull
	}
	return false
}

func (x *ColumnMetadata) GetDefault() []byte {
	if x != nil {
		return x.Default
	}
	return nil
}

func (x *ColumnMetadata) GetDefaultExpr() string {
	if x != nil {
		return x.DefaultExpr
	}
	return ""
}

type ColumnKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number  int32 `protobuf:"varint,1,opt,name=Number,proto3" json:"Number,omitempty"`
	Reverse bool  `protobuf:"varint,2,opt,name=Reverse,proto3" json:"Reverse,omitempty"`
}

func (x *ColumnKey) Reset() {
	*x = ColumnKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_typemd_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ColumnKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnKey) ProtoMessage() {}

func (x *ColumnKey) ProtoReflect() protoreflect.Message {
	mi := &file_typemd_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnKey.ProtoReflect.Descriptor instead.
func (*ColumnKey) Descriptor() ([]byte, []int) {
	return file_typemd_proto_rawDescGZIP(), []int{2}
}

func (x *ColumnKey) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *ColumnKey) GetReverse() bool {
	if x != nil {
		return x.Reverse
	}
	return false
}

type IndexMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string       `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Key    []*ColumnKey `protobuf:"bytes,2,rep,name=Key,proto3" json:"Key,omitempty"`
	Unique bool         `protobuf:"varint,3,opt,name=Unique,proto3" json:"Unique,omitempty"`
}

func (x *IndexMetadata) Reset() {
	*x = IndexMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_typemd_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IndexMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexMetadata) ProtoMessage() {}

func (x *IndexMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_typemd_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexMetadata.ProtoReflect.Descriptor instead.
func (*IndexMetadata) Descriptor() ([]byte, []int) {
	return file_typemd_proto_rawDescGZIP(), []int{3}
}

func (x *IndexMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IndexMetadata) GetKey() []*ColumnKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *IndexMetadata) GetUnique() bool {
	if x != nil {
		return x.Unique
	}
	return false
}

type ConstraintMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string         `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Type   ConstraintType `protobuf:"varint,2,opt,name=Type,proto3,enum=ConstraintType" json:"Type,omitempty"`
	ColNum int32          `protobuf:"varint,3,opt,name=ColNum,proto3" json:"ColNum,omitempty"`
}

func (x *ConstraintMetadata) Reset() {
	*x = ConstraintMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_typemd_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConstraintMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConstraintMetadata) ProtoMessage() {}

func (x *ConstraintMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_typemd_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConstraintMetadata.ProtoReflect.Descriptor instead.
func (*ConstraintMetadata) Descriptor() ([]byte, []int) {
	return file_typemd_proto_rawDescGZIP(), []int{4}
}

func (x *ConstraintMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConstraintMetadata) GetType() ConstraintType {
	if x != nil {
		return x.Type
	}
	return ConstraintType_UnknownConstraint
}

func (x *ConstraintMetadata) GetColNum() int32 {
	if x != nil {
		return x.ColNum
	}
	return 0
}

type CheckConstraint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Check     []byte `protobuf:"bytes,2,opt,name=Check,proto3" json:"Check,omitempty"`
	CheckExpr string `protobuf:"bytes,3,opt,name=CheckExpr,proto3" json:"CheckExpr,omitempty"`
}

func (x *CheckConstraint) Reset() {
	*x = CheckConstraint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_typemd_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckConstraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckConstraint) ProtoMessage() {}

func (x *CheckConstraint) ProtoReflect() protoreflect.Message {
	mi := &file_typemd_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckConstraint.ProtoReflect.Descriptor instead.
func (*CheckConstraint) Descriptor() ([]byte, []int) {
	return file_typemd_proto_rawDescGZIP(), []int{5}
}

func (x *CheckConstraint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CheckConstraint) GetCheck() []byte {
	if x != nil {
		return x.Check
	}
	return nil
}

func (x *CheckConstraint) GetCheckExpr() string {
	if x != nil {
		return x.CheckExpr
	}
	return ""
}

type TableName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Database string `protobuf:"bytes,1,opt,name=Database,proto3" json:"Database,omitempty"`
	Schema   string `protobuf:"bytes,2,opt,name=Schema,proto3" json:"Schema,omitempty"`
	Table    string `protobuf:"bytes,3,opt,name=Table,proto3" json:"Table,omitempty"`
}

func (x *TableName) Reset() {
	*x = TableName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_typemd_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TableName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableName) ProtoMessage() {}

func (x *TableName) ProtoReflect() protoreflect.Message {
	mi := &file_typemd_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableName.ProtoReflect.Descriptor instead.
func (*TableName) Descriptor() ([]byte, []int) {
	return file_typemd_proto_rawDescGZIP(), []int{6}
}

func (x *TableName) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *TableName) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *TableName) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

type ForeignKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name           string     `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	KeyColumns     []int32    `protobuf:"varint,2,rep,packed,name=KeyColumns,proto3" json:"KeyColumns,omitempty"`
	ReferenceTable *TableName `protobuf:"bytes,3,opt,name=ReferenceTable,proto3" json:"ReferenceTable,omitempty"`
	ReferenceIndex string     `protobuf:"bytes,4,opt,name=ReferenceIndex,proto3" json:"ReferenceIndex,omitempty"`
}

func (x *ForeignKey) Reset() {
	*x = ForeignKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_typemd_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForeignKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForeignKey) ProtoMessage() {}

func (x *ForeignKey) ProtoReflect() protoreflect.Message {
	mi := &file_typemd_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForeignKey.ProtoReflect.Descriptor instead.
func (*ForeignKey) Descriptor() ([]byte, []int) {
	return file_typemd_proto_rawDescGZIP(), []int{7}
}

func (x *ForeignKey) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ForeignKey) GetKeyColumns() []int32 {
	if x != nil {
		return x.KeyColumns
	}
	return nil
}

func (x *ForeignKey) GetReferenceTable() *TableName {
	if x != nil {
		return x.ReferenceTable
	}
	return nil
}

func (x *ForeignKey) GetReferenceIndex() string {
	if x != nil {
		return x.ReferenceIndex
	}
	return ""
}

type TriggerMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    string `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Events  int64  `protobuf:"varint,3,opt,name=Events,proto3" json:"Events,omitempty"`
	Trigger []byte `protobuf:"bytes,4,opt,name=Trigger,proto3" json:"Trigger,omitempty"`
}

func (x *TriggerMetadata) Reset() {
	*x = TriggerMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_typemd_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TriggerMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerMetadata) ProtoMessage() {}

func (x *TriggerMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_typemd_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerMetadata.ProtoReflect.Descriptor instead.
func (*TriggerMetadata) Descriptor() ([]byte, []int) {
	return file_typemd_proto_rawDescGZIP(), []int{8}
}

func (x *TriggerMetadata) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TriggerMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TriggerMetadata) GetEvents() int64 {
	if x != nil {
		return x.Events
	}
	return 0
}

func (x *TriggerMetadata) GetTrigger() []byte {
	if x != nil {
		return x.Trigger
	}
	return nil
}

var File_typemd_proto protoreflect.FileDescriptor

var file_typemd_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x74, 0x79, 0x70, 0x65, 0x6d, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe6,
	0x02, 0x0a, 0x11, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x4d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x29,
	0x0a, 0x07, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x52, 0x07, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x12, 0x24, 0x0a, 0x07, 0x50, 0x72, 0x69,
	0x6d, 0x61, 0x72, 0x79, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x43, 0x6f, 0x6c,
	0x75, 0x6d, 0x6e, 0x4b, 0x65, 0x79, 0x52, 0x07, 0x50, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x12,
	0x28, 0x0a, 0x07, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x52, 0x07, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x73, 0x12, 0x35, 0x0a, 0x0b, 0x43, 0x6f, 0x6e,
	0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x52, 0x0b, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x73,
	0x12, 0x28, 0x0a, 0x06, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69,
	0x6e, 0x74, 0x52, 0x06, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x12, 0x2d, 0x0a, 0x0b, 0x46, 0x6f,
	0x72, 0x65, 0x69, 0x67, 0x6e, 0x4b, 0x65, 0x79, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x46, 0x6f, 0x72, 0x65, 0x69, 0x67, 0x6e, 0x4b, 0x65, 0x79, 0x52, 0x0b, 0x46, 0x6f,
	0x72, 0x65, 0x69, 0x67, 0x6e, 0x4b, 0x65, 0x79, 0x73, 0x12, 0x2c, 0x0a, 0x08, 0x54, 0x72, 0x69,
	0x67, 0x67, 0x65, 0x72, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x54, 0x72,
	0x69, 0x67, 0x67, 0x65, 0x72, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x54,
	0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x73, 0x22, 0xc3, 0x01, 0x0a, 0x0e, 0x43, 0x6f, 0x6c, 0x75,
	0x6d, 0x6e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d,
	0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x09, 0x2e, 0x44,
	0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x53, 0x69, 0x7a,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x46, 0x69, 0x78, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x05, 0x46, 0x69, 0x78, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x4e, 0x6f, 0x74, 0x4e, 0x75,
	0x6c, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x4e, 0x6f, 0x74, 0x4e, 0x75, 0x6c,
	0x6c, 0x12, 0x18, 0x0a, 0x07, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x07, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x44,
	0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x45, 0x78, 0x70, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x45, 0x78, 0x70, 0x72, 0x22, 0x3d, 0x0a,
	0x09, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x4b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x52, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x52, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x22, 0x59, 0x0a, 0x0d,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1c, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a,
	0x2e, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x4b, 0x65, 0x79, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12,
	0x16, 0x0a, 0x06, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x22, 0x65, 0x0a, 0x12, 0x43, 0x6f, 0x6e, 0x73, 0x74,
	0x72, 0x61, 0x69, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x23, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0f, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x6f, 0x6c, 0x4e, 0x75, 0x6d,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x43, 0x6f, 0x6c, 0x4e, 0x75, 0x6d, 0x22, 0x59,
	0x0a, 0x0f, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x1c, 0x0a, 0x09, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x45, 0x78, 0x70, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x45, 0x78, 0x70, 0x72, 0x22, 0x55, 0x0a, 0x09, 0x54, 0x61, 0x62,
	0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61,
	0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x61,
	0x62, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x61, 0x62, 0x6c, 0x65,
	0x22, 0x9c, 0x01, 0x0a, 0x0a, 0x46, 0x6f, 0x72, 0x65, 0x69, 0x67, 0x6e, 0x4b, 0x65, 0x79, 0x12,
	0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x4b, 0x65, 0x79, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0a, 0x4b, 0x65, 0x79, 0x43, 0x6f, 0x6c, 0x75,
	0x6d, 0x6e, 0x73, 0x12, 0x32, 0x0a, 0x0e, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65,
	0x54, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x54, 0x61,
	0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x0e, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e,
	0x63, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x52, 0x65, 0x66, 0x65, 0x72,
	0x65, 0x6e, 0x63, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0e, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x22,
	0x6b, 0x0a, 0x0f, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x07, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x2a, 0x53, 0x0a, 0x08,
	0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x6e, 0x6b, 0x6e,
	0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x42, 0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e,
	0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x10, 0x02, 0x12, 0x09,
	0x0a, 0x05, 0x42, 0x79, 0x74, 0x65, 0x73, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x46, 0x6c, 0x6f,
	0x61, 0x74, 0x10, 0x04, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72, 0x10,
	0x05, 0x2a, 0x72, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x15, 0x0a, 0x11, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x43, 0x6f,
	0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x65,
	0x66, 0x61, 0x75, 0x6c, 0x74, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x4e, 0x6f, 0x74, 0x4e, 0x75,
	0x6c, 0x6c, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x10,
	0x03, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x10, 0x04, 0x12, 0x09, 0x0a,
	0x05, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x10, 0x05, 0x12, 0x0b, 0x0a, 0x07, 0x46, 0x6f, 0x72, 0x65,
	0x69, 0x67, 0x6e, 0x10, 0x06, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x65, 0x6e, 0x67, 0x69, 0x6e,
	0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_typemd_proto_rawDescOnce sync.Once
	file_typemd_proto_rawDescData = file_typemd_proto_rawDesc
)

func file_typemd_proto_rawDescGZIP() []byte {
	file_typemd_proto_rawDescOnce.Do(func() {
		file_typemd_proto_rawDescData = protoimpl.X.CompressGZIP(file_typemd_proto_rawDescData)
	})
	return file_typemd_proto_rawDescData
}

var file_typemd_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_typemd_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_typemd_proto_goTypes = []interface{}{
	(DataType)(0),              // 0: DataType
	(ConstraintType)(0),        // 1: ConstraintType
	(*TableTypeMetadata)(nil),  // 2: TableTypeMetadata
	(*ColumnMetadata)(nil),     // 3: ColumnMetadata
	(*ColumnKey)(nil),          // 4: ColumnKey
	(*IndexMetadata)(nil),      // 5: IndexMetadata
	(*ConstraintMetadata)(nil), // 6: ConstraintMetadata
	(*CheckConstraint)(nil),    // 7: CheckConstraint
	(*TableName)(nil),          // 8: TableName
	(*ForeignKey)(nil),         // 9: ForeignKey
	(*TriggerMetadata)(nil),    // 10: TriggerMetadata
}
var file_typemd_proto_depIdxs = []int32{
	3,  // 0: TableTypeMetadata.Columns:type_name -> ColumnMetadata
	4,  // 1: TableTypeMetadata.Primary:type_name -> ColumnKey
	5,  // 2: TableTypeMetadata.Indexes:type_name -> IndexMetadata
	6,  // 3: TableTypeMetadata.Constraints:type_name -> ConstraintMetadata
	7,  // 4: TableTypeMetadata.Checks:type_name -> CheckConstraint
	9,  // 5: TableTypeMetadata.ForeignKeys:type_name -> ForeignKey
	10, // 6: TableTypeMetadata.Triggers:type_name -> TriggerMetadata
	0,  // 7: ColumnMetadata.Type:type_name -> DataType
	4,  // 8: IndexMetadata.Key:type_name -> ColumnKey
	1,  // 9: ConstraintMetadata.Type:type_name -> ConstraintType
	8,  // 10: ForeignKey.ReferenceTable:type_name -> TableName
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_typemd_proto_init() }
func file_typemd_proto_init() {
	if File_typemd_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_typemd_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TableTypeMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_typemd_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ColumnMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_typemd_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ColumnKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_typemd_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IndexMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_typemd_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConstraintMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_typemd_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckConstraint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_typemd_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TableName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_typemd_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ForeignKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_typemd_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TriggerMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_typemd_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_typemd_proto_goTypes,
		DependencyIndexes: file_typemd_proto_depIdxs,
		EnumInfos:         file_typemd_proto_enumTypes,
		MessageInfos:      file_typemd_proto_msgTypes,
	}.Build()
	File_typemd_proto = out.File
	file_typemd_proto_rawDesc = nil
	file_typemd_proto_goTypes = nil
	file_typemd_proto_depIdxs = nil
}
