// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0-devel
// 	protoc        v3.11.4
// source: layoutmd.proto

package storage

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type TableLayoutMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NextIID int64   `protobuf:"varint,1,opt,name=NextIID,proto3" json:"NextIID,omitempty"`
	IIDs    []int64 `protobuf:"varint,2,rep,packed,name=IIDs,proto3" json:"IIDs,omitempty"`
}

func (x *TableLayoutMetadata) Reset() {
	*x = TableLayoutMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_layoutmd_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TableLayoutMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableLayoutMetadata) ProtoMessage() {}

func (x *TableLayoutMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_layoutmd_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableLayoutMetadata.ProtoReflect.Descriptor instead.
func (*TableLayoutMetadata) Descriptor() ([]byte, []int) {
	return file_layoutmd_proto_rawDescGZIP(), []int{0}
}

func (x *TableLayoutMetadata) GetNextIID() int64 {
	if x != nil {
		return x.NextIID
	}
	return 0
}

func (x *TableLayoutMetadata) GetIIDs() []int64 {
	if x != nil {
		return x.IIDs
	}
	return nil
}

var File_layoutmd_proto protoreflect.FileDescriptor

var file_layoutmd_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x6d, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x43, 0x0a, 0x13, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x4e, 0x65, 0x78, 0x74, 0x49,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x4e, 0x65, 0x78, 0x74, 0x49, 0x49,
	0x44, 0x12, 0x12, 0x0a, 0x04, 0x49, 0x49, 0x44, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52,
	0x04, 0x49, 0x49, 0x44, 0x73, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_layoutmd_proto_rawDescOnce sync.Once
	file_layoutmd_proto_rawDescData = file_layoutmd_proto_rawDesc
)

func file_layoutmd_proto_rawDescGZIP() []byte {
	file_layoutmd_proto_rawDescOnce.Do(func() {
		file_layoutmd_proto_rawDescData = protoimpl.X.CompressGZIP(file_layoutmd_proto_rawDescData)
	})
	return file_layoutmd_proto_rawDescData
}

var file_layoutmd_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_layoutmd_proto_goTypes = []interface{}{
	(*TableLayoutMetadata)(nil), // 0: TableLayoutMetadata
}
var file_layoutmd_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_layoutmd_proto_init() }
func file_layoutmd_proto_init() {
	if File_layoutmd_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_layoutmd_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TableLayoutMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_layoutmd_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_layoutmd_proto_goTypes,
		DependencyIndexes: file_layoutmd_proto_depIdxs,
		MessageInfos:      file_layoutmd_proto_msgTypes,
	}.Build()
	File_layoutmd_proto = out.File
	file_layoutmd_proto_rawDesc = nil
	file_layoutmd_proto_goTypes = nil
	file_layoutmd_proto_depIdxs = nil
}
