package test

import (
	"testing"

	"github.com/leftmike/maho/sql"
	"github.com/leftmike/maho/storage"
)

var (
	indexLifecycleTests = []interface{}{
		"createDatabase",

		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdCreateTable, name: sql.ID("tbl-a")},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdRemoveIndex, name: sql.ID("tbl-a"), idxname: sql.ID("idx-1"),
				fail: true},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdAddIndex, name: sql.ID("tbl-a"), idxname: sql.ID("idx-1"),
				key: []sql.ColumnKey{sql.MakeColumnKey(1, false)}},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdAddIndex, name: sql.ID("tbl-a"), idxname: sql.ID("idx-1"),
				key: []sql.ColumnKey{sql.MakeColumnKey(1, false)}, fail: true},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdRemoveIndex, name: sql.ID("tbl-a"), idxname: sql.ID("idx-1")},
			{fln: fln(), cmd: cmdNextStmt},
			{fln: fln(), cmd: cmdRemoveIndex, name: sql.ID("tbl-a"), idxname: sql.ID("idx-1"),
				fail: true},
			{fln: fln(), cmd: cmdCommit},
		},
	}
)

func RunIndexLifecycleTest(t *testing.T, st *storage.Store) {
	t.Helper()

	dbname := sql.ID("index_lifecycle_test")
	for _, test := range indexLifecycleTests {
		runTest(t, st, dbname, test)
	}
}

var (
	indexOneColUniqueTests = []interface{}{
		"createDatabase",

		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdCreateTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdAddIndex, name: sql.ID("tbl-b"), idxname: sql.ID("idx-1"),
				key: []sql.ColumnKey{sql.MakeColumnKey(1, false)}, unique: true},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdInsert, row: []sql.Value{i64Val(1), i64Val(10), strVal("_1_")}},
			{fln: fln(), cmd: cmdInsert, row: []sql.Value{i64Val(2), i64Val(20), strVal("_2_")}},
			{fln: fln(), cmd: cmdInsert, row: []sql.Value{i64Val(3), i64Val(30), strVal("_3_")}},
			{fln: fln(), cmd: cmdInsert, row: []sql.Value{i64Val(4), i64Val(40), strVal("_4_")}},
			{fln: fln(), cmd: cmdInsert, row: []sql.Value{i64Val(5), i64Val(50), strVal("_5_")}},
			{fln: fln(), cmd: cmdInsert, row: []sql.Value{i64Val(6), i64Val(60), strVal("_6_")}},
			{fln: fln(), cmd: cmdInsert, row: []sql.Value{i64Val(7), i64Val(70), strVal("_7_")}},
			{fln: fln(), cmd: cmdInsert, row: []sql.Value{i64Val(8), i64Val(80), strVal("_8_")}},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdRows,
				values: [][]sql.Value{
					{i64Val(1), i64Val(10), strVal("_1_")},
					{i64Val(2), i64Val(20), strVal("_2_")},
					{i64Val(3), i64Val(30), strVal("_3_")},
					{i64Val(4), i64Val(40), strVal("_4_")},
					{i64Val(5), i64Val(50), strVal("_5_")},
					{i64Val(6), i64Val(60), strVal("_6_")},
					{i64Val(7), i64Val(70), strVal("_7_")},
					{i64Val(8), i64Val(80), strVal("_8_")},
				},
			},
			{fln: fln(), cmd: cmdIndexRows, idxname: sql.ID("idx-1"),
				idxValues: [][]sql.Value{
					{i64Val(10), i64Val(1)},
					{i64Val(20), i64Val(2)},
					{i64Val(30), i64Val(3)},
					{i64Val(40), i64Val(4)},
					{i64Val(50), i64Val(5)},
					{i64Val(60), i64Val(6)},
					{i64Val(70), i64Val(7)},
					{i64Val(80), i64Val(8)},
				},
				values: [][]sql.Value{
					{i64Val(1), i64Val(10), strVal("_1_")},
					{i64Val(2), i64Val(20), strVal("_2_")},
					{i64Val(3), i64Val(30), strVal("_3_")},
					{i64Val(4), i64Val(40), strVal("_4_")},
					{i64Val(5), i64Val(50), strVal("_5_")},
					{i64Val(6), i64Val(60), strVal("_6_")},
					{i64Val(7), i64Val(70), strVal("_7_")},
					{i64Val(8), i64Val(80), strVal("_8_")},
				},
			},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdInsert,
				row: []sql.Value{i64Val(9), i64Val(80), strVal("_9_")}, fail: true},
			{fln: fln(), cmd: cmdRollback},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdInsert,
				row: []sql.Value{i64Val(9), i64Val(70), strVal("_8_")}, fail: true},
			{fln: fln(), cmd: cmdRollback},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdRows,
				values: [][]sql.Value{
					{i64Val(1), i64Val(10), strVal("_1_")},
					{i64Val(2), i64Val(20), strVal("_2_")},
					{i64Val(3), i64Val(30), strVal("_3_")},
					{i64Val(4), i64Val(40), strVal("_4_")},
					{i64Val(5), i64Val(50), strVal("_5_")},
					{i64Val(6), i64Val(60), strVal("_6_")},
					{i64Val(7), i64Val(70), strVal("_7_")},
					{i64Val(8), i64Val(80), strVal("_8_")},
				},
			},
			{fln: fln(), cmd: cmdIndexRows, idxname: sql.ID("idx-1"),
				idxValues: [][]sql.Value{
					{i64Val(10), i64Val(1)},
					{i64Val(20), i64Val(2)},
					{i64Val(30), i64Val(3)},
					{i64Val(40), i64Val(4)},
					{i64Val(50), i64Val(5)},
					{i64Val(60), i64Val(6)},
					{i64Val(70), i64Val(7)},
					{i64Val(80), i64Val(8)},
				},
				values: [][]sql.Value{
					{i64Val(1), i64Val(10), strVal("_1_")},
					{i64Val(2), i64Val(20), strVal("_2_")},
					{i64Val(3), i64Val(30), strVal("_3_")},
					{i64Val(4), i64Val(40), strVal("_4_")},
					{i64Val(5), i64Val(50), strVal("_5_")},
					{i64Val(6), i64Val(60), strVal("_6_")},
					{i64Val(7), i64Val(70), strVal("_7_")},
					{i64Val(8), i64Val(80), strVal("_8_")},
				},
			},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdUpdate, rowID: 4,
				updates: []sql.ColumnUpdate{{Column: 1, Value: i64Val(400)}}},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdUpdate, rowID: 1,
				updates: []sql.ColumnUpdate{{Column: 1, Value: i64Val(40)}}},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdRows,
				values: [][]sql.Value{
					{i64Val(1), i64Val(40), strVal("_1_")},
					{i64Val(2), i64Val(20), strVal("_2_")},
					{i64Val(3), i64Val(30), strVal("_3_")},
					{i64Val(4), i64Val(400), strVal("_4_")},
					{i64Val(5), i64Val(50), strVal("_5_")},
					{i64Val(6), i64Val(60), strVal("_6_")},
					{i64Val(7), i64Val(70), strVal("_7_")},
					{i64Val(8), i64Val(80), strVal("_8_")},
				},
			},
			{fln: fln(), cmd: cmdIndexRows, idxname: sql.ID("idx-1"),
				idxValues: [][]sql.Value{
					{i64Val(20), i64Val(2)},
					{i64Val(30), i64Val(3)},
					{i64Val(40), i64Val(1)},
					{i64Val(50), i64Val(5)},
					{i64Val(60), i64Val(6)},
					{i64Val(70), i64Val(7)},
					{i64Val(80), i64Val(8)},
					{i64Val(400), i64Val(4)},
				},
				values: [][]sql.Value{
					{i64Val(2), i64Val(20), strVal("_2_")},
					{i64Val(3), i64Val(30), strVal("_3_")},
					{i64Val(1), i64Val(40), strVal("_1_")},
					{i64Val(5), i64Val(50), strVal("_5_")},
					{i64Val(6), i64Val(60), strVal("_6_")},
					{i64Val(7), i64Val(70), strVal("_7_")},
					{i64Val(8), i64Val(80), strVal("_8_")},
					{i64Val(4), i64Val(400), strVal("_4_")},
				},
			},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdUpdate, rowID: 2,
				updates: []sql.ColumnUpdate{{Column: 1, Value: i64Val(40)}}, fail: true},
			{fln: fln(), cmd: cmdRollback},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdUpdate, rowID: 7,
				updates: []sql.ColumnUpdate{{Column: 1, Value: i64Val(400)}}, fail: true},
			{fln: fln(), cmd: cmdRollback},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdDelete, rowID: 1},
			{fln: fln(), cmd: cmdDelete, rowID: 4},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdRows,
				values: [][]sql.Value{
					{i64Val(2), i64Val(20), strVal("_2_")},
					{i64Val(3), i64Val(30), strVal("_3_")},
					{i64Val(5), i64Val(50), strVal("_5_")},
					{i64Val(6), i64Val(60), strVal("_6_")},
					{i64Val(7), i64Val(70), strVal("_7_")},
					{i64Val(8), i64Val(80), strVal("_8_")},
				},
			},
			{fln: fln(), cmd: cmdIndexRows, idxname: sql.ID("idx-1"),
				idxValues: [][]sql.Value{
					{i64Val(20), i64Val(2)},
					{i64Val(30), i64Val(3)},
					{i64Val(50), i64Val(5)},
					{i64Val(60), i64Val(6)},
					{i64Val(70), i64Val(7)},
					{i64Val(80), i64Val(8)},
				},
				values: [][]sql.Value{
					{i64Val(2), i64Val(20), strVal("_2_")},
					{i64Val(3), i64Val(30), strVal("_3_")},
					{i64Val(5), i64Val(50), strVal("_5_")},
					{i64Val(6), i64Val(60), strVal("_6_")},
					{i64Val(7), i64Val(70), strVal("_7_")},
					{i64Val(8), i64Val(80), strVal("_8_")},
				},
			},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdUpdate, rowID: 2,
				updates: []sql.ColumnUpdate{{Column: 1, Value: i64Val(40)}}},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdUpdate, rowID: 7,
				updates: []sql.ColumnUpdate{{Column: 1, Value: i64Val(400)}}},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdRows,
				values: [][]sql.Value{
					{i64Val(2), i64Val(40), strVal("_2_")},
					{i64Val(3), i64Val(30), strVal("_3_")},
					{i64Val(5), i64Val(50), strVal("_5_")},
					{i64Val(6), i64Val(60), strVal("_6_")},
					{i64Val(7), i64Val(400), strVal("_7_")},
					{i64Val(8), i64Val(80), strVal("_8_")},
				},
			},
			{fln: fln(), cmd: cmdIndexRows, idxname: sql.ID("idx-1"),
				idxValues: [][]sql.Value{
					{i64Val(30), i64Val(3)},
					{i64Val(40), i64Val(2)},
					{i64Val(50), i64Val(5)},
					{i64Val(60), i64Val(6)},
					{i64Val(80), i64Val(8)},
					{i64Val(400), i64Val(7)},
				},
				values: [][]sql.Value{
					{i64Val(3), i64Val(30), strVal("_3_")},
					{i64Val(2), i64Val(40), strVal("_2_")},
					{i64Val(5), i64Val(50), strVal("_5_")},
					{i64Val(6), i64Val(60), strVal("_6_")},
					{i64Val(8), i64Val(80), strVal("_8_")},
					{i64Val(7), i64Val(400), strVal("_7_")},
				},
			},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdIndexUpdate, idxname: sql.ID("idx-1"), rowID: 5,
				updates: []sql.ColumnUpdate{{Column: 1, Value: i64Val(400)}}, fail: true},
			{fln: fln(), cmd: cmdRollback},
		},

		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdIndexUpdate, idxname: sql.ID("idx-1"), rowID: 5,
				updates: []sql.ColumnUpdate{{Column: 0, Value: i64Val(8)}}, fail: true},
			{fln: fln(), cmd: cmdRollback},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdIndexUpdate, idxname: sql.ID("idx-1"), rowID: 5,
				updates: []sql.ColumnUpdate{{Column: 1, Value: i64Val(500)}}},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdRows,
				values: [][]sql.Value{
					{i64Val(2), i64Val(40), strVal("_2_")},
					{i64Val(3), i64Val(30), strVal("_3_")},
					{i64Val(5), i64Val(500), strVal("_5_")},
					{i64Val(6), i64Val(60), strVal("_6_")},
					{i64Val(7), i64Val(400), strVal("_7_")},
					{i64Val(8), i64Val(80), strVal("_8_")},
				},
			},
			{fln: fln(), cmd: cmdIndexRows, idxname: sql.ID("idx-1"),
				idxValues: [][]sql.Value{
					{i64Val(30), i64Val(3)},
					{i64Val(40), i64Val(2)},
					{i64Val(60), i64Val(6)},
					{i64Val(80), i64Val(8)},
					{i64Val(400), i64Val(7)},
					{i64Val(500), i64Val(5)},
				},
				values: [][]sql.Value{
					{i64Val(3), i64Val(30), strVal("_3_")},
					{i64Val(2), i64Val(40), strVal("_2_")},
					{i64Val(6), i64Val(60), strVal("_6_")},
					{i64Val(8), i64Val(80), strVal("_8_")},
					{i64Val(7), i64Val(400), strVal("_7_")},
					{i64Val(5), i64Val(500), strVal("_5_")},
				},
			},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdIndexDelete, idxname: sql.ID("idx-1"), rowID: 2},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdIndexUpdate, idxname: sql.ID("idx-1"), rowID: 8,
				updates: []sql.ColumnUpdate{{Column: 1, Value: i64Val(40)}}},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdRows,
				values: [][]sql.Value{
					{i64Val(3), i64Val(30), strVal("_3_")},
					{i64Val(5), i64Val(500), strVal("_5_")},
					{i64Val(6), i64Val(60), strVal("_6_")},
					{i64Val(7), i64Val(400), strVal("_7_")},
					{i64Val(8), i64Val(40), strVal("_8_")},
				},
			},
			{fln: fln(), cmd: cmdIndexRows, idxname: sql.ID("idx-1"),
				idxValues: [][]sql.Value{
					{i64Val(30), i64Val(3)},
					{i64Val(40), i64Val(8)},
					{i64Val(60), i64Val(6)},
					{i64Val(400), i64Val(7)},
					{i64Val(500), i64Val(5)},
				},
				values: [][]sql.Value{
					{i64Val(3), i64Val(30), strVal("_3_")},
					{i64Val(8), i64Val(40), strVal("_8_")},
					{i64Val(6), i64Val(60), strVal("_6_")},
					{i64Val(7), i64Val(400), strVal("_7_")},
					{i64Val(5), i64Val(500), strVal("_5_")},
				},
			},
			{fln: fln(), cmd: cmdCommit},
		},
	}
)

func RunIndexOneColUniqueTest(t *testing.T, st *storage.Store) {
	t.Helper()

	dbname := sql.ID("index_one_col_unique_test")
	for _, test := range indexOneColUniqueTests {
		runTest(t, st, dbname, test)
	}
}

var (
	indexTwoColUniqueTests = []interface{}{
		"createDatabase",

		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdCreateTable, name: sql.ID("tbl-b"),
				cols: []sql.Identifier{sql.ID("ID"), sql.ID("col2"), sql.ID("col3"),
					sql.ID("col4")},
				colTypes: []sql.ColumnType{int32ColType, int64ColType, stringColType,
					stringColType},
				key: []sql.ColumnKey{sql.MakeColumnKey(0, false)},
			},
			{fln: fln(), cmd: cmdAddIndex, name: sql.ID("tbl-b"), idxname: sql.ID("idx-1"),
				key:    []sql.ColumnKey{sql.MakeColumnKey(2, false), sql.MakeColumnKey(1, false)},
				unique: true},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdInsert,
				row: []sql.Value{i64Val(1), i64Val(10), strVal("_1_"), strVal("aaa")},
			},
			{fln: fln(), cmd: cmdInsert,
				row: []sql.Value{i64Val(2), i64Val(20), strVal("_2_"), strVal("bbb")},
			},
			{fln: fln(), cmd: cmdInsert,
				row: []sql.Value{i64Val(3), i64Val(30), strVal("_3_"), strVal("ccc")},
			},
			{fln: fln(), cmd: cmdInsert,
				row: []sql.Value{i64Val(4), i64Val(40), strVal("_4_"), strVal("ddd")},
			},
			{fln: fln(), cmd: cmdInsert,
				row: []sql.Value{i64Val(5), i64Val(50), strVal("_5_"), strVal("eee")},
			},
			{fln: fln(), cmd: cmdInsert,
				row: []sql.Value{i64Val(6), i64Val(60), strVal("_6_"), strVal("fff")},
			},
			{fln: fln(), cmd: cmdInsert,
				row: []sql.Value{i64Val(7), i64Val(70), strVal("_7_"), strVal("ggg")},
			},
			{fln: fln(), cmd: cmdInsert,
				row: []sql.Value{i64Val(8), i64Val(80), strVal("_8_"), strVal("hhh")},
			},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdRows,
				values: [][]sql.Value{
					{i64Val(1), i64Val(10), strVal("_1_"), strVal("aaa")},
					{i64Val(2), i64Val(20), strVal("_2_"), strVal("bbb")},
					{i64Val(3), i64Val(30), strVal("_3_"), strVal("ccc")},
					{i64Val(4), i64Val(40), strVal("_4_"), strVal("ddd")},
					{i64Val(5), i64Val(50), strVal("_5_"), strVal("eee")},
					{i64Val(6), i64Val(60), strVal("_6_"), strVal("fff")},
					{i64Val(7), i64Val(70), strVal("_7_"), strVal("ggg")},
					{i64Val(8), i64Val(80), strVal("_8_"), strVal("hhh")},
				},
			},
			{fln: fln(), cmd: cmdIndexRows, idxname: sql.ID("idx-1"),
				idxValues: [][]sql.Value{
					{strVal("_1_"), i64Val(10), i64Val(1)},
					{strVal("_2_"), i64Val(20), i64Val(2)},
					{strVal("_3_"), i64Val(30), i64Val(3)},
					{strVal("_4_"), i64Val(40), i64Val(4)},
					{strVal("_5_"), i64Val(50), i64Val(5)},
					{strVal("_6_"), i64Val(60), i64Val(6)},
					{strVal("_7_"), i64Val(70), i64Val(7)},
					{strVal("_8_"), i64Val(80), i64Val(8)},
				},
				values: [][]sql.Value{
					{i64Val(1), i64Val(10), strVal("_1_"), strVal("aaa")},
					{i64Val(2), i64Val(20), strVal("_2_"), strVal("bbb")},
					{i64Val(3), i64Val(30), strVal("_3_"), strVal("ccc")},
					{i64Val(4), i64Val(40), strVal("_4_"), strVal("ddd")},
					{i64Val(5), i64Val(50), strVal("_5_"), strVal("eee")},
					{i64Val(6), i64Val(60), strVal("_6_"), strVal("fff")},
					{i64Val(7), i64Val(70), strVal("_7_"), strVal("ggg")},
					{i64Val(8), i64Val(80), strVal("_8_"), strVal("hhh")},
				},
			},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdInsert,
				row: []sql.Value{i64Val(9), i64Val(80), strVal("_8_")}, fail: true},
			{fln: fln(), cmd: cmdRollback},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdInsert,
				row: []sql.Value{i64Val(8), i64Val(90), strVal("_90_")}, fail: true},
			{fln: fln(), cmd: cmdRollback},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdInsert,
				row: []sql.Value{i64Val(9), i64Val(90), strVal("_8_"), strVal("iii")}},
			{fln: fln(), cmd: cmdInsert,
				row: []sql.Value{i64Val(10), i64Val(10), strVal("_2_"), strVal("jjj")}},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdRows,
				values: [][]sql.Value{
					{i64Val(1), i64Val(10), strVal("_1_"), strVal("aaa")},
					{i64Val(2), i64Val(20), strVal("_2_"), strVal("bbb")},
					{i64Val(3), i64Val(30), strVal("_3_"), strVal("ccc")},
					{i64Val(4), i64Val(40), strVal("_4_"), strVal("ddd")},
					{i64Val(5), i64Val(50), strVal("_5_"), strVal("eee")},
					{i64Val(6), i64Val(60), strVal("_6_"), strVal("fff")},
					{i64Val(7), i64Val(70), strVal("_7_"), strVal("ggg")},
					{i64Val(8), i64Val(80), strVal("_8_"), strVal("hhh")},
					{i64Val(9), i64Val(90), strVal("_8_"), strVal("iii")},
					{i64Val(10), i64Val(10), strVal("_2_"), strVal("jjj")},
				},
			},
			{fln: fln(), cmd: cmdIndexRows, idxname: sql.ID("idx-1"),
				idxValues: [][]sql.Value{
					{strVal("_1_"), i64Val(10), i64Val(1)},
					{strVal("_2_"), i64Val(10), i64Val(10)},
					{strVal("_2_"), i64Val(20), i64Val(2)},
					{strVal("_3_"), i64Val(30), i64Val(3)},
					{strVal("_4_"), i64Val(40), i64Val(4)},
					{strVal("_5_"), i64Val(50), i64Val(5)},
					{strVal("_6_"), i64Val(60), i64Val(6)},
					{strVal("_7_"), i64Val(70), i64Val(7)},
					{strVal("_8_"), i64Val(80), i64Val(8)},
					{strVal("_8_"), i64Val(90), i64Val(9)},
				},
				values: [][]sql.Value{
					{i64Val(1), i64Val(10), strVal("_1_"), strVal("aaa")},
					{i64Val(10), i64Val(10), strVal("_2_"), strVal("jjj")},
					{i64Val(2), i64Val(20), strVal("_2_"), strVal("bbb")},
					{i64Val(3), i64Val(30), strVal("_3_"), strVal("ccc")},
					{i64Val(4), i64Val(40), strVal("_4_"), strVal("ddd")},
					{i64Val(5), i64Val(50), strVal("_5_"), strVal("eee")},
					{i64Val(6), i64Val(60), strVal("_6_"), strVal("fff")},
					{i64Val(7), i64Val(70), strVal("_7_"), strVal("ggg")},
					{i64Val(8), i64Val(80), strVal("_8_"), strVal("hhh")},
					{i64Val(9), i64Val(90), strVal("_8_"), strVal("iii")},
				},
			},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdUpdate, rowID: 4,
				updates: []sql.ColumnUpdate{
					{Column: 1, Value: i64Val(400)},
					{Column: 2, Value: strVal("_40_")},
					{Column: 3, Value: strVal("ddd-2")},
				},
			},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdUpdate, rowID: 1,
				updates: []sql.ColumnUpdate{
					{Column: 1, Value: i64Val(40)},
					{Column: 2, Value: strVal("_4_")},
					{Column: 3, Value: strVal("aaa-2")},
				},
			},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdUpdate, rowID: 10,
				updates: []sql.ColumnUpdate{
					{Column: 3, Value: strVal("jjj-2")},
				},
			},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdRows,
				values: [][]sql.Value{
					{i64Val(1), i64Val(40), strVal("_4_"), strVal("aaa-2")},
					{i64Val(2), i64Val(20), strVal("_2_"), strVal("bbb")},
					{i64Val(3), i64Val(30), strVal("_3_"), strVal("ccc")},
					{i64Val(4), i64Val(400), strVal("_40_"), strVal("ddd-2")},
					{i64Val(5), i64Val(50), strVal("_5_"), strVal("eee")},
					{i64Val(6), i64Val(60), strVal("_6_"), strVal("fff")},
					{i64Val(7), i64Val(70), strVal("_7_"), strVal("ggg")},
					{i64Val(8), i64Val(80), strVal("_8_"), strVal("hhh")},
					{i64Val(9), i64Val(90), strVal("_8_"), strVal("iii")},
					{i64Val(10), i64Val(10), strVal("_2_"), strVal("jjj-2")},
				},
			},
			{fln: fln(), cmd: cmdIndexRows, idxname: sql.ID("idx-1"),
				idxValues: [][]sql.Value{
					{strVal("_2_"), i64Val(10), i64Val(10)},
					{strVal("_2_"), i64Val(20), i64Val(2)},
					{strVal("_3_"), i64Val(30), i64Val(3)},
					{strVal("_40_"), i64Val(400), i64Val(4)},
					{strVal("_4_"), i64Val(40), i64Val(1)},
					{strVal("_5_"), i64Val(50), i64Val(5)},
					{strVal("_6_"), i64Val(60), i64Val(6)},
					{strVal("_7_"), i64Val(70), i64Val(7)},
					{strVal("_8_"), i64Val(80), i64Val(8)},
					{strVal("_8_"), i64Val(90), i64Val(9)},
				},
				values: [][]sql.Value{
					{i64Val(10), i64Val(10), strVal("_2_"), strVal("jjj-2")},
					{i64Val(2), i64Val(20), strVal("_2_"), strVal("bbb")},
					{i64Val(3), i64Val(30), strVal("_3_"), strVal("ccc")},
					{i64Val(4), i64Val(400), strVal("_40_"), strVal("ddd-2")},
					{i64Val(1), i64Val(40), strVal("_4_"), strVal("aaa-2")},
					{i64Val(5), i64Val(50), strVal("_5_"), strVal("eee")},
					{i64Val(6), i64Val(60), strVal("_6_"), strVal("fff")},
					{i64Val(7), i64Val(70), strVal("_7_"), strVal("ggg")},
					{i64Val(8), i64Val(80), strVal("_8_"), strVal("hhh")},
					{i64Val(9), i64Val(90), strVal("_8_"), strVal("iii")},
				},
			},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdUpdate, rowID: 2,
				updates: []sql.ColumnUpdate{
					{Column: 1, Value: i64Val(40)},
					{Column: 2, Value: strVal("_4_")},
				},
				fail: true,
			},
			{fln: fln(), cmd: cmdRollback},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdUpdate, rowID: 7,
				updates: []sql.ColumnUpdate{
					{Column: 1, Value: i64Val(400)},
					{Column: 2, Value: strVal("_40_")},
				},
				fail: true,
			},
			{fln: fln(), cmd: cmdRollback},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdDelete, rowID: 1},
			{fln: fln(), cmd: cmdDelete, rowID: 4},
			{fln: fln(), cmd: cmdDelete, rowID: 9},
			{fln: fln(), cmd: cmdDelete, rowID: 10},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdRows,
				values: [][]sql.Value{
					{i64Val(2), i64Val(20), strVal("_2_"), strVal("bbb")},
					{i64Val(3), i64Val(30), strVal("_3_"), strVal("ccc")},
					{i64Val(5), i64Val(50), strVal("_5_"), strVal("eee")},
					{i64Val(6), i64Val(60), strVal("_6_"), strVal("fff")},
					{i64Val(7), i64Val(70), strVal("_7_"), strVal("ggg")},
					{i64Val(8), i64Val(80), strVal("_8_"), strVal("hhh")},
				},
			},
			{fln: fln(), cmd: cmdIndexRows, idxname: sql.ID("idx-1"),
				idxValues: [][]sql.Value{
					{strVal("_2_"), i64Val(20), i64Val(2)},
					{strVal("_3_"), i64Val(30), i64Val(3)},
					{strVal("_5_"), i64Val(50), i64Val(5)},
					{strVal("_6_"), i64Val(60), i64Val(6)},
					{strVal("_7_"), i64Val(70), i64Val(7)},
					{strVal("_8_"), i64Val(80), i64Val(8)},
				},
				values: [][]sql.Value{
					{i64Val(2), i64Val(20), strVal("_2_"), strVal("bbb")},
					{i64Val(3), i64Val(30), strVal("_3_"), strVal("ccc")},
					{i64Val(5), i64Val(50), strVal("_5_"), strVal("eee")},
					{i64Val(6), i64Val(60), strVal("_6_"), strVal("fff")},
					{i64Val(7), i64Val(70), strVal("_7_"), strVal("ggg")},
					{i64Val(8), i64Val(80), strVal("_8_"), strVal("hhh")},
				},
			},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdUpdate, rowID: 2,
				updates: []sql.ColumnUpdate{
					{Column: 1, Value: i64Val(40)},
					{Column: 2, Value: strVal("_4_")},
				},
			},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdUpdate, rowID: 7,
				updates: []sql.ColumnUpdate{
					{Column: 1, Value: i64Val(400)},
					{Column: 2, Value: strVal("_40_")},
				},
			},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdRows,
				values: [][]sql.Value{
					{i64Val(2), i64Val(40), strVal("_4_"), strVal("bbb")},
					{i64Val(3), i64Val(30), strVal("_3_"), strVal("ccc")},
					{i64Val(5), i64Val(50), strVal("_5_"), strVal("eee")},
					{i64Val(6), i64Val(60), strVal("_6_"), strVal("fff")},
					{i64Val(7), i64Val(400), strVal("_40_"), strVal("ggg")},
					{i64Val(8), i64Val(80), strVal("_8_"), strVal("hhh")},
				},
			},
			{fln: fln(), cmd: cmdIndexRows, idxname: sql.ID("idx-1"),
				idxValues: [][]sql.Value{
					{strVal("_3_"), i64Val(30), i64Val(3)},
					{strVal("_40_"), i64Val(400), i64Val(7)},
					{strVal("_4_"), i64Val(40), i64Val(2)},
					{strVal("_5_"), i64Val(50), i64Val(5)},
					{strVal("_6_"), i64Val(60), i64Val(6)},
					{strVal("_8_"), i64Val(80), i64Val(8)},
				},
				values: [][]sql.Value{
					{i64Val(3), i64Val(30), strVal("_3_"), strVal("ccc")},
					{i64Val(7), i64Val(400), strVal("_40_"), strVal("ggg")},
					{i64Val(2), i64Val(40), strVal("_4_"), strVal("bbb")},
					{i64Val(5), i64Val(50), strVal("_5_"), strVal("eee")},
					{i64Val(6), i64Val(60), strVal("_6_"), strVal("fff")},
					{i64Val(8), i64Val(80), strVal("_8_"), strVal("hhh")},
				},
			},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdIndexDelete, idxname: sql.ID("idx-1"), rowID: 7},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdIndexUpdate, idxname: sql.ID("idx-1"), rowID: 5,
				updates: []sql.ColumnUpdate{
					{Column: 1, Value: i64Val(80)},
					{Column: 2, Value: strVal("_8_")},
				},
				fail: true,
			},
			{fln: fln(), cmd: cmdRollback},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdIndexUpdate, idxname: sql.ID("idx-1"), rowID: 5,
				updates: []sql.ColumnUpdate{
					{Column: 1, Value: i64Val(8)},
					{Column: 2, Value: strVal("_8_")},
				},
			},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdIndexUpdate, idxname: sql.ID("idx-1"), rowID: 6,
				updates: []sql.ColumnUpdate{
					{Column: 3, Value: strVal("fff-2")},
				},
			},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdRows,
				values: [][]sql.Value{
					{i64Val(2), i64Val(40), strVal("_4_"), strVal("bbb")},
					{i64Val(3), i64Val(30), strVal("_3_"), strVal("ccc")},
					{i64Val(5), i64Val(8), strVal("_8_"), strVal("eee")},
					{i64Val(6), i64Val(60), strVal("_6_"), strVal("fff-2")},
					{i64Val(8), i64Val(80), strVal("_8_"), strVal("hhh")},
				},
			},
			{fln: fln(), cmd: cmdIndexRows, idxname: sql.ID("idx-1"),
				idxValues: [][]sql.Value{
					{strVal("_3_"), i64Val(30), i64Val(3)},
					{strVal("_4_"), i64Val(40), i64Val(2)},
					{strVal("_6_"), i64Val(60), i64Val(6)},
					{strVal("_8_"), i64Val(8), i64Val(5)},
					{strVal("_8_"), i64Val(80), i64Val(8)},
				},
				values: [][]sql.Value{
					{i64Val(3), i64Val(30), strVal("_3_"), strVal("ccc")},
					{i64Val(2), i64Val(40), strVal("_4_"), strVal("bbb")},
					{i64Val(6), i64Val(60), strVal("_6_"), strVal("fff-2")},
					{i64Val(5), i64Val(8), strVal("_8_"), strVal("eee")},
					{i64Val(8), i64Val(80), strVal("_8_"), strVal("hhh")},
				},
			},
			{fln: fln(), cmd: cmdCommit},
		},
	}
)

func RunIndexTwoColUniqueTest(t *testing.T, st *storage.Store) {
	t.Helper()

	dbname := sql.ID("index_two_col_unique_test")
	for _, test := range indexTwoColUniqueTests {
		runTest(t, st, dbname, test)
	}
}

var (
	indexOneColTests = []interface{}{
		"createDatabase",

		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdCreateTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdAddIndex, name: sql.ID("tbl-b"), idxname: sql.ID("idx-1"),
				key: []sql.ColumnKey{sql.MakeColumnKey(1, false)}},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdInsert, row: []sql.Value{i64Val(1), i64Val(10), strVal("_1_")}},
			{fln: fln(), cmd: cmdInsert, row: []sql.Value{i64Val(2), i64Val(20), strVal("_2_")}},
			{fln: fln(), cmd: cmdInsert, row: []sql.Value{i64Val(3), i64Val(30), strVal("_3_")}},
			{fln: fln(), cmd: cmdInsert, row: []sql.Value{i64Val(4), i64Val(40), strVal("_4_")}},
			{fln: fln(), cmd: cmdInsert, row: []sql.Value{i64Val(5), i64Val(50), strVal("_5_")}},
			{fln: fln(), cmd: cmdInsert, row: []sql.Value{i64Val(6), i64Val(60), strVal("_6_")}},
			{fln: fln(), cmd: cmdInsert, row: []sql.Value{i64Val(7), i64Val(70), strVal("_7_")}},
			{fln: fln(), cmd: cmdInsert, row: []sql.Value{i64Val(8), i64Val(80), strVal("_8_")}},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdRows,
				values: [][]sql.Value{
					{i64Val(1), i64Val(10), strVal("_1_")},
					{i64Val(2), i64Val(20), strVal("_2_")},
					{i64Val(3), i64Val(30), strVal("_3_")},
					{i64Val(4), i64Val(40), strVal("_4_")},
					{i64Val(5), i64Val(50), strVal("_5_")},
					{i64Val(6), i64Val(60), strVal("_6_")},
					{i64Val(7), i64Val(70), strVal("_7_")},
					{i64Val(8), i64Val(80), strVal("_8_")},
				},
			},
			{fln: fln(), cmd: cmdIndexRows, idxname: sql.ID("idx-1"),
				idxValues: [][]sql.Value{
					{i64Val(10), i64Val(1)},
					{i64Val(20), i64Val(2)},
					{i64Val(30), i64Val(3)},
					{i64Val(40), i64Val(4)},
					{i64Val(50), i64Val(5)},
					{i64Val(60), i64Val(6)},
					{i64Val(70), i64Val(7)},
					{i64Val(80), i64Val(8)},
				},
				values: [][]sql.Value{
					{i64Val(1), i64Val(10), strVal("_1_")},
					{i64Val(2), i64Val(20), strVal("_2_")},
					{i64Val(3), i64Val(30), strVal("_3_")},
					{i64Val(4), i64Val(40), strVal("_4_")},
					{i64Val(5), i64Val(50), strVal("_5_")},
					{i64Val(6), i64Val(60), strVal("_6_")},
					{i64Val(7), i64Val(70), strVal("_7_")},
					{i64Val(8), i64Val(80), strVal("_8_")},
				},
			},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdInsert,
				row: []sql.Value{i64Val(9), i64Val(80), strVal("_9_")}},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdInsert,
				row: []sql.Value{i64Val(10), i64Val(10), strVal("_10_")}},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdRows,
				values: [][]sql.Value{
					{i64Val(1), i64Val(10), strVal("_1_")},
					{i64Val(2), i64Val(20), strVal("_2_")},
					{i64Val(3), i64Val(30), strVal("_3_")},
					{i64Val(4), i64Val(40), strVal("_4_")},
					{i64Val(5), i64Val(50), strVal("_5_")},
					{i64Val(6), i64Val(60), strVal("_6_")},
					{i64Val(7), i64Val(70), strVal("_7_")},
					{i64Val(8), i64Val(80), strVal("_8_")},
					{i64Val(9), i64Val(80), strVal("_9_")},
					{i64Val(10), i64Val(10), strVal("_10_")},
				},
			},
			{fln: fln(), cmd: cmdIndexRows, idxname: sql.ID("idx-1"),
				idxValues: [][]sql.Value{
					{i64Val(10), i64Val(1)},
					{i64Val(10), i64Val(10)},
					{i64Val(20), i64Val(2)},
					{i64Val(30), i64Val(3)},
					{i64Val(40), i64Val(4)},
					{i64Val(50), i64Val(5)},
					{i64Val(60), i64Val(6)},
					{i64Val(70), i64Val(7)},
					{i64Val(80), i64Val(8)},
					{i64Val(80), i64Val(9)},
				},
				values: [][]sql.Value{
					{i64Val(1), i64Val(10), strVal("_1_")},
					{i64Val(10), i64Val(10), strVal("_10_")},
					{i64Val(2), i64Val(20), strVal("_2_")},
					{i64Val(3), i64Val(30), strVal("_3_")},
					{i64Val(4), i64Val(40), strVal("_4_")},
					{i64Val(5), i64Val(50), strVal("_5_")},
					{i64Val(6), i64Val(60), strVal("_6_")},
					{i64Val(7), i64Val(70), strVal("_7_")},
					{i64Val(8), i64Val(80), strVal("_8_")},
					{i64Val(9), i64Val(80), strVal("_9_")},
				},
			},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdUpdate, rowID: 1,
				updates: []sql.ColumnUpdate{{Column: 1, Value: i64Val(40)}}},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdRows,
				values: [][]sql.Value{
					{i64Val(1), i64Val(40), strVal("_1_")},
					{i64Val(2), i64Val(20), strVal("_2_")},
					{i64Val(3), i64Val(30), strVal("_3_")},
					{i64Val(4), i64Val(40), strVal("_4_")},
					{i64Val(5), i64Val(50), strVal("_5_")},
					{i64Val(6), i64Val(60), strVal("_6_")},
					{i64Val(7), i64Val(70), strVal("_7_")},
					{i64Val(8), i64Val(80), strVal("_8_")},
					{i64Val(9), i64Val(80), strVal("_9_")},
					{i64Val(10), i64Val(10), strVal("_10_")},
				},
			},
			{fln: fln(), cmd: cmdIndexRows, idxname: sql.ID("idx-1"),
				idxValues: [][]sql.Value{
					{i64Val(10), i64Val(10)},
					{i64Val(20), i64Val(2)},
					{i64Val(30), i64Val(3)},
					{i64Val(40), i64Val(1)},
					{i64Val(40), i64Val(4)},
					{i64Val(50), i64Val(5)},
					{i64Val(60), i64Val(6)},
					{i64Val(70), i64Val(7)},
					{i64Val(80), i64Val(8)},
					{i64Val(80), i64Val(9)},
				},
				values: [][]sql.Value{
					{i64Val(10), i64Val(10), strVal("_10_")},
					{i64Val(2), i64Val(20), strVal("_2_")},
					{i64Val(3), i64Val(30), strVal("_3_")},
					{i64Val(1), i64Val(40), strVal("_1_")},
					{i64Val(4), i64Val(40), strVal("_4_")},
					{i64Val(5), i64Val(50), strVal("_5_")},
					{i64Val(6), i64Val(60), strVal("_6_")},
					{i64Val(7), i64Val(70), strVal("_7_")},
					{i64Val(8), i64Val(80), strVal("_8_")},
					{i64Val(9), i64Val(80), strVal("_9_")},
				},
			},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdUpdate, rowID: 2,
				updates: []sql.ColumnUpdate{{Column: 1, Value: i64Val(40)}}},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdUpdate, rowID: 7,
				updates: []sql.ColumnUpdate{{Column: 1, Value: i64Val(40)}}},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdRows,
				values: [][]sql.Value{
					{i64Val(1), i64Val(40), strVal("_1_")},
					{i64Val(2), i64Val(40), strVal("_2_")},
					{i64Val(3), i64Val(30), strVal("_3_")},
					{i64Val(4), i64Val(40), strVal("_4_")},
					{i64Val(5), i64Val(50), strVal("_5_")},
					{i64Val(6), i64Val(60), strVal("_6_")},
					{i64Val(7), i64Val(40), strVal("_7_")},
					{i64Val(8), i64Val(80), strVal("_8_")},
					{i64Val(9), i64Val(80), strVal("_9_")},
					{i64Val(10), i64Val(10), strVal("_10_")},
				},
			},
			{fln: fln(), cmd: cmdIndexRows, idxname: sql.ID("idx-1"),
				idxValues: [][]sql.Value{
					{i64Val(10), i64Val(10)},
					{i64Val(30), i64Val(3)},
					{i64Val(40), i64Val(1)},
					{i64Val(40), i64Val(2)},
					{i64Val(40), i64Val(4)},
					{i64Val(40), i64Val(7)},
					{i64Val(50), i64Val(5)},
					{i64Val(60), i64Val(6)},
					{i64Val(80), i64Val(8)},
					{i64Val(80), i64Val(9)},
				},
				values: [][]sql.Value{
					{i64Val(10), i64Val(10), strVal("_10_")},
					{i64Val(3), i64Val(30), strVal("_3_")},
					{i64Val(1), i64Val(40), strVal("_1_")},
					{i64Val(2), i64Val(40), strVal("_2_")},
					{i64Val(4), i64Val(40), strVal("_4_")},
					{i64Val(7), i64Val(40), strVal("_7_")},
					{i64Val(5), i64Val(50), strVal("_5_")},
					{i64Val(6), i64Val(60), strVal("_6_")},
					{i64Val(8), i64Val(80), strVal("_8_")},
					{i64Val(9), i64Val(80), strVal("_9_")},
				},
			},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdIndexUpdate, idxname: sql.ID("idx-1"), rowID: 1,
				updates: []sql.ColumnUpdate{{Column: 1, Value: i64Val(10)}}},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdIndexUpdate, idxname: sql.ID("idx-1"), rowID: 9,
				updates: []sql.ColumnUpdate{{Column: 1, Value: i64Val(40)}}},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdRows,
				values: [][]sql.Value{
					{i64Val(1), i64Val(10), strVal("_1_")},
					{i64Val(2), i64Val(40), strVal("_2_")},
					{i64Val(3), i64Val(30), strVal("_3_")},
					{i64Val(4), i64Val(40), strVal("_4_")},
					{i64Val(5), i64Val(50), strVal("_5_")},
					{i64Val(6), i64Val(60), strVal("_6_")},
					{i64Val(7), i64Val(40), strVal("_7_")},
					{i64Val(8), i64Val(80), strVal("_8_")},
					{i64Val(9), i64Val(40), strVal("_9_")},
					{i64Val(10), i64Val(10), strVal("_10_")},
				},
			},
			{fln: fln(), cmd: cmdIndexRows, idxname: sql.ID("idx-1"),
				idxValues: [][]sql.Value{
					{i64Val(10), i64Val(1)},
					{i64Val(10), i64Val(10)},
					{i64Val(30), i64Val(3)},
					{i64Val(40), i64Val(2)},
					{i64Val(40), i64Val(4)},
					{i64Val(40), i64Val(7)},
					{i64Val(40), i64Val(9)},
					{i64Val(50), i64Val(5)},
					{i64Val(60), i64Val(6)},
					{i64Val(80), i64Val(8)},
				},
				values: [][]sql.Value{
					{i64Val(1), i64Val(10), strVal("_1_")},
					{i64Val(10), i64Val(10), strVal("_10_")},
					{i64Val(3), i64Val(30), strVal("_3_")},
					{i64Val(2), i64Val(40), strVal("_2_")},
					{i64Val(4), i64Val(40), strVal("_4_")},
					{i64Val(7), i64Val(40), strVal("_7_")},
					{i64Val(9), i64Val(40), strVal("_9_")},
					{i64Val(5), i64Val(50), strVal("_5_")},
					{i64Val(6), i64Val(60), strVal("_6_")},
					{i64Val(8), i64Val(80), strVal("_8_")},
				},
			},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdIndexDelete, idxname: sql.ID("idx-1"), rowID: 2},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdIndexDelete, idxname: sql.ID("idx-1"), rowID: 8},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdRows,
				values: [][]sql.Value{
					{i64Val(1), i64Val(10), strVal("_1_")},
					{i64Val(3), i64Val(30), strVal("_3_")},
					{i64Val(4), i64Val(40), strVal("_4_")},
					{i64Val(5), i64Val(50), strVal("_5_")},
					{i64Val(6), i64Val(60), strVal("_6_")},
					{i64Val(7), i64Val(40), strVal("_7_")},
					{i64Val(9), i64Val(40), strVal("_9_")},
					{i64Val(10), i64Val(10), strVal("_10_")},
				},
			},
			{fln: fln(), cmd: cmdIndexRows, idxname: sql.ID("idx-1"),
				idxValues: [][]sql.Value{
					{i64Val(10), i64Val(1)},
					{i64Val(10), i64Val(10)},
					{i64Val(30), i64Val(3)},
					{i64Val(40), i64Val(4)},
					{i64Val(40), i64Val(7)},
					{i64Val(40), i64Val(9)},
					{i64Val(50), i64Val(5)},
					{i64Val(60), i64Val(6)},
				},
				values: [][]sql.Value{
					{i64Val(1), i64Val(10), strVal("_1_")},
					{i64Val(10), i64Val(10), strVal("_10_")},
					{i64Val(3), i64Val(30), strVal("_3_")},
					{i64Val(4), i64Val(40), strVal("_4_")},
					{i64Val(7), i64Val(40), strVal("_7_")},
					{i64Val(9), i64Val(40), strVal("_9_")},
					{i64Val(5), i64Val(50), strVal("_5_")},
					{i64Val(6), i64Val(60), strVal("_6_")},
				},
			},
			{fln: fln(), cmd: cmdCommit},
		},
	}
)

func RunIndexOneColTest(t *testing.T, st *storage.Store) {
	t.Helper()

	dbname := sql.ID("index_one_col_test")
	for _, test := range indexOneColTests {
		runTest(t, st, dbname, test)
	}
}

var (
	indexTwoColTests = []interface{}{
		"createDatabase",

		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdCreateTable, name: sql.ID("tbl-b"),
				cols: []sql.Identifier{sql.ID("ID"), sql.ID("col2"), sql.ID("col3"),
					sql.ID("col4")},
				colTypes: []sql.ColumnType{int32ColType, int64ColType, stringColType,
					stringColType},
				key: []sql.ColumnKey{sql.MakeColumnKey(0, false)},
			},
			{fln: fln(), cmd: cmdAddIndex, name: sql.ID("tbl-b"), idxname: sql.ID("idx-1"),
				key: []sql.ColumnKey{sql.MakeColumnKey(2, false), sql.MakeColumnKey(1, false)}},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdInsert,
				row: []sql.Value{i64Val(1), i64Val(10), strVal("_1_"), strVal("aaa")},
			},
			{fln: fln(), cmd: cmdInsert,
				row: []sql.Value{i64Val(2), i64Val(20), strVal("_2_"), strVal("bbb")},
			},
			{fln: fln(), cmd: cmdInsert,
				row: []sql.Value{i64Val(3), i64Val(30), strVal("_3_"), strVal("ccc")},
			},
			{fln: fln(), cmd: cmdInsert,
				row: []sql.Value{i64Val(4), i64Val(40), strVal("_4_"), strVal("ddd")},
			},
			{fln: fln(), cmd: cmdInsert,
				row: []sql.Value{i64Val(5), i64Val(50), strVal("_5_"), strVal("eee")},
			},
			{fln: fln(), cmd: cmdInsert,
				row: []sql.Value{i64Val(6), i64Val(60), strVal("_6_"), strVal("fff")},
			},
			{fln: fln(), cmd: cmdInsert,
				row: []sql.Value{i64Val(7), i64Val(70), strVal("_7_"), strVal("ggg")},
			},
			{fln: fln(), cmd: cmdInsert,
				row: []sql.Value{i64Val(8), i64Val(80), strVal("_8_"), strVal("hhh")},
			},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdRows,
				values: [][]sql.Value{
					{i64Val(1), i64Val(10), strVal("_1_"), strVal("aaa")},
					{i64Val(2), i64Val(20), strVal("_2_"), strVal("bbb")},
					{i64Val(3), i64Val(30), strVal("_3_"), strVal("ccc")},
					{i64Val(4), i64Val(40), strVal("_4_"), strVal("ddd")},
					{i64Val(5), i64Val(50), strVal("_5_"), strVal("eee")},
					{i64Val(6), i64Val(60), strVal("_6_"), strVal("fff")},
					{i64Val(7), i64Val(70), strVal("_7_"), strVal("ggg")},
					{i64Val(8), i64Val(80), strVal("_8_"), strVal("hhh")},
				},
			},
			{fln: fln(), cmd: cmdIndexRows, idxname: sql.ID("idx-1"),
				idxValues: [][]sql.Value{
					{strVal("_1_"), i64Val(10), i64Val(1)},
					{strVal("_2_"), i64Val(20), i64Val(2)},
					{strVal("_3_"), i64Val(30), i64Val(3)},
					{strVal("_4_"), i64Val(40), i64Val(4)},
					{strVal("_5_"), i64Val(50), i64Val(5)},
					{strVal("_6_"), i64Val(60), i64Val(6)},
					{strVal("_7_"), i64Val(70), i64Val(7)},
					{strVal("_8_"), i64Val(80), i64Val(8)},
				},
				values: [][]sql.Value{
					{i64Val(1), i64Val(10), strVal("_1_"), strVal("aaa")},
					{i64Val(2), i64Val(20), strVal("_2_"), strVal("bbb")},
					{i64Val(3), i64Val(30), strVal("_3_"), strVal("ccc")},
					{i64Val(4), i64Val(40), strVal("_4_"), strVal("ddd")},
					{i64Val(5), i64Val(50), strVal("_5_"), strVal("eee")},
					{i64Val(6), i64Val(60), strVal("_6_"), strVal("fff")},
					{i64Val(7), i64Val(70), strVal("_7_"), strVal("ggg")},
					{i64Val(8), i64Val(80), strVal("_8_"), strVal("hhh")},
				},
			},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdInsert,
				row: []sql.Value{i64Val(9), i64Val(80), strVal("_8_"), strVal("iii")},
			},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdInsert, row: []sql.Value{i64Val(9), i64Val(70), strVal("_7_")},
				fail: true},
			{fln: fln(), cmd: cmdRollback},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdInsert,
				row: []sql.Value{i64Val(10), i64Val(90), strVal("_8_"), strVal("jjj")},
			},
			{fln: fln(), cmd: cmdInsert,
				row: []sql.Value{i64Val(11), i64Val(10), strVal("_1_"), strVal("kkk")},
			},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdIndexUpdate, rowID: 4, idxname: sql.ID("idx-1"),
				updates: []sql.ColumnUpdate{
					{Column: 1, Value: i64Val(20)},
					{Column: 2, Value: strVal("_2_")},
					{Column: 3, Value: strVal("ddd-2")},
				},
			},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdIndexUpdate, rowID: 9, idxname: sql.ID("idx-1"),
				updates: []sql.ColumnUpdate{
					{Column: 3, Value: strVal("iii-2")},
				},
			},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdIndexUpdate, rowID: 1, idxname: sql.ID("idx-1"),
				updates: []sql.ColumnUpdate{
					{Column: 1, Value: i64Val(20)},
					{Column: 2, Value: strVal("_2_")},
				},
			},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdIndexDelete, rowID: 3, idxname: sql.ID("idx-1")},
			{fln: fln(), cmd: cmdDelete, rowID: 6},
			{fln: fln(), cmd: cmdIndexDelete, rowID: 7, idxname: sql.ID("idx-1")},
			{fln: fln(), cmd: cmdCommit},
		},
		[]storeCmd{
			{fln: fln(), cmd: cmdBegin},
			{fln: fln(), cmd: cmdLookupTable, name: sql.ID("tbl-b")},
			{fln: fln(), cmd: cmdRows,
				values: [][]sql.Value{
					{i64Val(1), i64Val(20), strVal("_2_"), strVal("aaa")},
					{i64Val(2), i64Val(20), strVal("_2_"), strVal("bbb")},
					{i64Val(4), i64Val(20), strVal("_2_"), strVal("ddd-2")},
					{i64Val(5), i64Val(50), strVal("_5_"), strVal("eee")},
					{i64Val(8), i64Val(80), strVal("_8_"), strVal("hhh")},
					{i64Val(9), i64Val(80), strVal("_8_"), strVal("iii-2")},
					{i64Val(10), i64Val(90), strVal("_8_"), strVal("jjj")},
					{i64Val(11), i64Val(10), strVal("_1_"), strVal("kkk")},
				},
			},
			{fln: fln(), cmd: cmdIndexRows, idxname: sql.ID("idx-1"),
				idxValues: [][]sql.Value{
					{strVal("_1_"), i64Val(10), i64Val(11)},
					{strVal("_2_"), i64Val(20), i64Val(1)},
					{strVal("_2_"), i64Val(20), i64Val(2)},
					{strVal("_2_"), i64Val(20), i64Val(4)},
					{strVal("_5_"), i64Val(50), i64Val(5)},
					{strVal("_8_"), i64Val(80), i64Val(8)},
					{strVal("_8_"), i64Val(80), i64Val(9)},
					{strVal("_8_"), i64Val(90), i64Val(10)},
				},
				values: [][]sql.Value{
					{i64Val(11), i64Val(10), strVal("_1_"), strVal("kkk")},
					{i64Val(1), i64Val(20), strVal("_2_"), strVal("aaa")},
					{i64Val(2), i64Val(20), strVal("_2_"), strVal("bbb")},
					{i64Val(4), i64Val(20), strVal("_2_"), strVal("ddd-2")},
					{i64Val(5), i64Val(50), strVal("_5_"), strVal("eee")},
					{i64Val(8), i64Val(80), strVal("_8_"), strVal("hhh")},
					{i64Val(9), i64Val(80), strVal("_8_"), strVal("iii-2")},
					{i64Val(10), i64Val(90), strVal("_8_"), strVal("jjj")},
				},
			},
			{fln: fln(), cmd: cmdCommit},
		},
	}
)

func RunIndexTwoColTest(t *testing.T, st *storage.Store) {
	t.Helper()

	dbname := sql.ID("index_two_col_test")
	for _, test := range indexTwoColTests {
		runTest(t, st, dbname, test)
	}
}
