// Code generated by protoc-gen-go. DO NOT EDIT.
// source: metadata.proto

package encoding

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Type int32

const (
	Type_UnknownType          Type = 0
	Type_DatabaseMetadataType Type = 1
	Type_TableMetadataType    Type = 2
	Type_TransactionType      Type = 3
	Type_ProposalType         Type = 4
	Type_MaximumType          Type = 4
)

var Type_name = map[int32]string{
	0: "UnknownType",
	1: "DatabaseMetadataType",
	2: "TableMetadataType",
	3: "TransactionType",
	4: "ProposalType",
	// Duplicate value: 4: "MaximumType",
}

var Type_value = map[string]int32{
	"UnknownType":          0,
	"DatabaseMetadataType": 1,
	"TableMetadataType":    2,
	"TransactionType":      3,
	"ProposalType":         4,
	"MaximumType":          4,
}

func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}

func (Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{0}
}

// These need to match the values in maho/sql/datatype.go
type DataType int32

const (
	DataType_Unknown   DataType = 0
	DataType_Boolean   DataType = 1
	DataType_Character DataType = 2
	DataType_Float     DataType = 3
	DataType_Integer   DataType = 4
)

var DataType_name = map[int32]string{
	0: "Unknown",
	1: "Boolean",
	2: "Character",
	3: "Float",
	4: "Integer",
}

var DataType_value = map[string]int32{
	"Unknown":   0,
	"Boolean":   1,
	"Character": 2,
	"Float":     3,
	"Integer":   4,
}

func (x DataType) String() string {
	return proto.EnumName(DataType_name, int32(x))
}

func (DataType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{1}
}

type TransactionState int32

const (
	TransactionState_Active    TransactionState = 0
	TransactionState_Committed TransactionState = 1
	TransactionState_Aborted   TransactionState = 2
)

var TransactionState_name = map[int32]string{
	0: "Active",
	1: "Committed",
	2: "Aborted",
}

var TransactionState_value = map[string]int32{
	"Active":    0,
	"Committed": 1,
	"Aborted":   2,
}

func (x TransactionState) String() string {
	return proto.EnumName(TransactionState_name, int32(x))
}

func (TransactionState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{2}
}

type DatabaseMetadata struct {
	Type                 uint32   `protobuf:"varint,1,opt,name=Type,proto3" json:"Type,omitempty"`
	DatabaseVersion      uint32   `protobuf:"varint,2,opt,name=DatabaseVersion,proto3" json:"DatabaseVersion,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Opens                uint64   `protobuf:"varint,4,opt,name=Opens,proto3" json:"Opens,omitempty"`
	NextTableID          uint32   `protobuf:"varint,5,opt,name=NextTableID,proto3" json:"NextTableID,omitempty"`
	Version              uint64   `protobuf:"varint,6,opt,name=Version,proto3" json:"Version,omitempty"`
	NextRowID            uint64   `protobuf:"varint,7,opt,name=NextRowID,proto3" json:"NextRowID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DatabaseMetadata) Reset()         { *m = DatabaseMetadata{} }
func (m *DatabaseMetadata) String() string { return proto.CompactTextString(m) }
func (*DatabaseMetadata) ProtoMessage()    {}
func (*DatabaseMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{0}
}

func (m *DatabaseMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatabaseMetadata.Unmarshal(m, b)
}
func (m *DatabaseMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatabaseMetadata.Marshal(b, m, deterministic)
}
func (m *DatabaseMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatabaseMetadata.Merge(m, src)
}
func (m *DatabaseMetadata) XXX_Size() int {
	return xxx_messageInfo_DatabaseMetadata.Size(m)
}
func (m *DatabaseMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_DatabaseMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_DatabaseMetadata proto.InternalMessageInfo

func (m *DatabaseMetadata) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *DatabaseMetadata) GetDatabaseVersion() uint32 {
	if m != nil {
		return m.DatabaseVersion
	}
	return 0
}

func (m *DatabaseMetadata) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DatabaseMetadata) GetOpens() uint64 {
	if m != nil {
		return m.Opens
	}
	return 0
}

func (m *DatabaseMetadata) GetNextTableID() uint32 {
	if m != nil {
		return m.NextTableID
	}
	return 0
}

func (m *DatabaseMetadata) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *DatabaseMetadata) GetNextRowID() uint64 {
	if m != nil {
		return m.NextRowID
	}
	return 0
}

type TableMetadata struct {
	Type                 uint32            `protobuf:"varint,1,opt,name=Type,proto3" json:"Type,omitempty"`
	ID                   uint32            `protobuf:"varint,2,opt,name=ID,proto3" json:"ID,omitempty"`
	Columns              []*ColumnMetadata `protobuf:"bytes,3,rep,name=Columns,proto3" json:"Columns,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TableMetadata) Reset()         { *m = TableMetadata{} }
func (m *TableMetadata) String() string { return proto.CompactTextString(m) }
func (*TableMetadata) ProtoMessage()    {}
func (*TableMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{1}
}

func (m *TableMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TableMetadata.Unmarshal(m, b)
}
func (m *TableMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TableMetadata.Marshal(b, m, deterministic)
}
func (m *TableMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TableMetadata.Merge(m, src)
}
func (m *TableMetadata) XXX_Size() int {
	return xxx_messageInfo_TableMetadata.Size(m)
}
func (m *TableMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_TableMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_TableMetadata proto.InternalMessageInfo

func (m *TableMetadata) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *TableMetadata) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *TableMetadata) GetColumns() []*ColumnMetadata {
	if m != nil {
		return m.Columns
	}
	return nil
}

type ColumnMetadata struct {
	Name  string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Index uint32   `protobuf:"varint,2,opt,name=Index,proto3" json:"Index,omitempty"`
	Type  DataType `protobuf:"varint,3,opt,name=Type,proto3,enum=DataType" json:"Type,omitempty"`
	// Size of the column in bytes for integers and in characters for character columns
	Size                 uint32   `protobuf:"varint,4,opt,name=Size,proto3" json:"Size,omitempty"`
	Fixed                bool     `protobuf:"varint,5,opt,name=Fixed,proto3" json:"Fixed,omitempty"`
	Binary               bool     `protobuf:"varint,6,opt,name=Binary,proto3" json:"Binary,omitempty"`
	NotNull              bool     `protobuf:"varint,7,opt,name=NotNull,proto3" json:"NotNull,omitempty"`
	Default              string   `protobuf:"bytes,8,opt,name=Default,proto3" json:"Default,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ColumnMetadata) Reset()         { *m = ColumnMetadata{} }
func (m *ColumnMetadata) String() string { return proto.CompactTextString(m) }
func (*ColumnMetadata) ProtoMessage()    {}
func (*ColumnMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{2}
}

func (m *ColumnMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ColumnMetadata.Unmarshal(m, b)
}
func (m *ColumnMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ColumnMetadata.Marshal(b, m, deterministic)
}
func (m *ColumnMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ColumnMetadata.Merge(m, src)
}
func (m *ColumnMetadata) XXX_Size() int {
	return xxx_messageInfo_ColumnMetadata.Size(m)
}
func (m *ColumnMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_ColumnMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_ColumnMetadata proto.InternalMessageInfo

func (m *ColumnMetadata) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ColumnMetadata) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *ColumnMetadata) GetType() DataType {
	if m != nil {
		return m.Type
	}
	return DataType_Unknown
}

func (m *ColumnMetadata) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ColumnMetadata) GetFixed() bool {
	if m != nil {
		return m.Fixed
	}
	return false
}

func (m *ColumnMetadata) GetBinary() bool {
	if m != nil {
		return m.Binary
	}
	return false
}

func (m *ColumnMetadata) GetNotNull() bool {
	if m != nil {
		return m.NotNull
	}
	return false
}

func (m *ColumnMetadata) GetDefault() string {
	if m != nil {
		return m.Default
	}
	return ""
}

type Transaction struct {
	Type  uint32 `protobuf:"varint,1,opt,name=Type,proto3" json:"Type,omitempty"`
	State uint32 `protobuf:"varint,2,opt,name=State,proto3" json:"State,omitempty"`
	// At which open; used to detect stale transactions from previous opens of the database
	At                   uint64   `protobuf:"varint,3,opt,name=At,proto3" json:"At,omitempty"`
	Version              uint64   `protobuf:"varint,4,opt,name=Version,proto3" json:"Version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{3}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Transaction) GetState() uint32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *Transaction) GetAt() uint64 {
	if m != nil {
		return m.At
	}
	return 0
}

func (m *Transaction) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

type Proposal struct {
	Type                 uint32   `protobuf:"varint,1,opt,name=Type,proto3" json:"Type,omitempty"`
	TransactionKey       []byte   `protobuf:"bytes,2,opt,name=TransactionKey,proto3" json:"TransactionKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Proposal) Reset()         { *m = Proposal{} }
func (m *Proposal) String() string { return proto.CompactTextString(m) }
func (*Proposal) ProtoMessage()    {}
func (*Proposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{4}
}

func (m *Proposal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Proposal.Unmarshal(m, b)
}
func (m *Proposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Proposal.Marshal(b, m, deterministic)
}
func (m *Proposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Proposal.Merge(m, src)
}
func (m *Proposal) XXX_Size() int {
	return xxx_messageInfo_Proposal.Size(m)
}
func (m *Proposal) XXX_DiscardUnknown() {
	xxx_messageInfo_Proposal.DiscardUnknown(m)
}

var xxx_messageInfo_Proposal proto.InternalMessageInfo

func (m *Proposal) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Proposal) GetTransactionKey() []byte {
	if m != nil {
		return m.TransactionKey
	}
	return nil
}

func init() {
	proto.RegisterEnum("Type", Type_name, Type_value)
	proto.RegisterEnum("DataType", DataType_name, DataType_value)
	proto.RegisterEnum("TransactionState", TransactionState_name, TransactionState_value)
	proto.RegisterType((*DatabaseMetadata)(nil), "DatabaseMetadata")
	proto.RegisterType((*TableMetadata)(nil), "TableMetadata")
	proto.RegisterType((*ColumnMetadata)(nil), "ColumnMetadata")
	proto.RegisterType((*Transaction)(nil), "Transaction")
	proto.RegisterType((*Proposal)(nil), "Proposal")
}

func init() { proto.RegisterFile("metadata.proto", fileDescriptor_56d9f74966f40d04) }

var fileDescriptor_56d9f74966f40d04 = []byte{
	// 537 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0xc1, 0x8f, 0xd2, 0x4e,
	0x14, 0xde, 0x29, 0x05, 0xca, 0x63, 0x81, 0xf9, 0xcd, 0x0f, 0x4d, 0x63, 0x34, 0x21, 0x1c, 0x0c,
	0x72, 0xe0, 0xb0, 0xde, 0xbc, 0xc1, 0x36, 0x24, 0xcd, 0x66, 0xd1, 0xcc, 0xa2, 0x07, 0x0f, 0x26,
	0x03, 0x8c, 0x6b, 0x63, 0x3b, 0x43, 0xda, 0xc1, 0x05, 0xcf, 0xfe, 0x7f, 0x5e, 0xfc, 0x83, 0xcc,
	0xbc, 0x76, 0x14, 0xd0, 0x78, 0x9b, 0xef, 0x7b, 0x33, 0xef, 0x7d, 0xdf, 0xf7, 0x5a, 0xe8, 0x66,
	0xd2, 0x88, 0x8d, 0x30, 0x62, 0xb2, 0xcd, 0xb5, 0xd1, 0xc3, 0x1f, 0x04, 0x68, 0x24, 0x8c, 0x58,
	0x89, 0x42, 0xde, 0x56, 0x25, 0xc6, 0xc0, 0x5f, 0x1e, 0xb6, 0x32, 0x24, 0x03, 0x32, 0xea, 0x70,
	0x3c, 0xb3, 0x11, 0xf4, 0xdc, 0xbd, 0x77, 0x32, 0x2f, 0x12, 0xad, 0x42, 0x0f, 0xcb, 0xe7, 0xb4,
	0x7d, 0xbd, 0x10, 0x99, 0x0c, 0x6b, 0x03, 0x32, 0x6a, 0x71, 0x3c, 0xb3, 0x3e, 0xd4, 0x5f, 0x6f,
	0xa5, 0x2a, 0x42, 0x7f, 0x40, 0x46, 0x3e, 0x2f, 0x01, 0x1b, 0x40, 0x7b, 0x21, 0xf7, 0x66, 0x29,
	0x56, 0xa9, 0x8c, 0xa3, 0xb0, 0x8e, 0xfd, 0x8e, 0x29, 0x16, 0x42, 0xd3, 0x4d, 0x6b, 0xe0, 0x4b,
	0x07, 0xd9, 0x53, 0x68, 0xd9, 0x8b, 0x5c, 0x3f, 0xc4, 0x51, 0xd8, 0xc4, 0xda, 0x6f, 0x62, 0xf8,
	0x01, 0x3a, 0xd8, 0xe2, 0x9f, 0x96, 0xba, 0xe0, 0xc5, 0x51, 0xe5, 0xc2, 0x8b, 0x23, 0xf6, 0x02,
	0x9a, 0xd7, 0x3a, 0xdd, 0x65, 0xaa, 0x08, 0x6b, 0x83, 0xda, 0xa8, 0x7d, 0xd5, 0x9b, 0x94, 0xd8,
	0x75, 0xe1, 0xae, 0x3e, 0xfc, 0x4e, 0xa0, 0x7b, 0x5a, 0xfb, 0x65, 0x9b, 0x9c, 0xda, 0x8e, 0xd5,
	0x46, 0xee, 0xab, 0x21, 0x25, 0x60, 0xcf, 0x2a, 0x2d, 0x36, 0xa0, 0xee, 0x55, 0x6b, 0x62, 0x03,
	0xb4, 0x44, 0x25, 0x8b, 0x81, 0x7f, 0x97, 0x7c, 0x95, 0x18, 0x55, 0x87, 0xe3, 0xd9, 0x36, 0x9a,
	0x27, 0x7b, 0xb9, 0xc1, 0x8c, 0x02, 0x5e, 0x02, 0xf6, 0x18, 0x1a, 0xb3, 0x44, 0x89, 0xfc, 0x80,
	0xe1, 0x04, 0xbc, 0x42, 0x36, 0xb5, 0x85, 0x36, 0x8b, 0x5d, 0x9a, 0x62, 0x32, 0x01, 0x77, 0xd0,
	0x56, 0x22, 0xf9, 0x51, 0xec, 0x52, 0x13, 0x06, 0xa8, 0xd3, 0xc1, 0xa1, 0x80, 0xf6, 0x32, 0x17,
	0xaa, 0x10, 0x6b, 0x53, 0x2d, 0xf1, 0x8f, 0xbc, 0xfa, 0x50, 0xbf, 0x33, 0xc2, 0x48, 0xe7, 0x06,
	0x81, 0x4d, 0x71, 0x6a, 0xd0, 0x8b, 0xcf, 0xbd, 0xa9, 0x39, 0x5e, 0x99, 0x7f, 0xb2, 0xb2, 0xe1,
	0x1c, 0x82, 0x37, 0xb9, 0xde, 0xea, 0x42, 0xa4, 0x7f, 0xed, 0xff, 0x1c, 0xba, 0x47, 0x12, 0x6e,
	0xe4, 0x01, 0x07, 0x5d, 0xf2, 0x33, 0x76, 0xfc, 0x8d, 0x94, 0x8f, 0x59, 0x0f, 0xda, 0x6f, 0xd5,
	0x67, 0xa5, 0x1f, 0x94, 0x85, 0xf4, 0x82, 0x85, 0xd0, 0x3f, 0xff, 0x98, 0xb1, 0x42, 0xd8, 0x23,
	0xf8, 0xef, 0xe4, 0x83, 0x40, 0xda, 0x63, 0xff, 0x43, 0xef, 0xa8, 0x39, 0x92, 0x35, 0x46, 0xe1,
	0xd2, 0xe9, 0x44, 0xc6, 0xb7, 0x83, 0x6e, 0xc5, 0x3e, 0xc9, 0x76, 0x59, 0x49, 0x3c, 0xf1, 0x28,
	0x19, 0xdf, 0x40, 0xe0, 0x36, 0xc7, 0xda, 0xd0, 0xac, 0x94, 0xd0, 0x0b, 0x0b, 0x66, 0x5a, 0xa7,
	0x52, 0x28, 0x4a, 0x58, 0x07, 0x5a, 0xd7, 0x9f, 0x44, 0x2e, 0xd6, 0x46, 0xe6, 0xd4, 0x63, 0x2d,
	0xa8, 0xcf, 0x53, 0x2d, 0x0c, 0xad, 0xd9, 0x6b, 0xb1, 0x32, 0xf2, 0x5e, 0xe6, 0xd4, 0x1f, 0xbf,
	0x02, 0x7a, 0x24, 0xa4, 0x4c, 0x16, 0xa0, 0x31, 0x5d, 0x9b, 0xe4, 0x8b, 0x75, 0x66, 0xdb, 0xe8,
	0x2c, 0x4b, 0x8c, 0x91, 0x1b, 0x4a, 0xec, 0xdb, 0xe9, 0x4a, 0xe7, 0x16, 0x78, 0x33, 0x78, 0x1f,
	0x48, 0xb5, 0xd6, 0x9b, 0x44, 0xdd, 0xaf, 0x1a, 0xf8, 0x5b, 0xbf, 0xfc, 0x19, 0x00, 0x00, 0xff,
	0xff, 0xb3, 0xff, 0x91, 0xe0, 0xe8, 0x03, 0x00, 0x00,
}
