// Code generated by protoc-gen-go. DO NOT EDIT.
// source: metadata.proto

package encoding

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// These need to match the values in maho/sql/datatype.go
type DataType int32

const (
	DataType_Unknown   DataType = 0
	DataType_Boolean   DataType = 1
	DataType_Character DataType = 2
	DataType_Float     DataType = 3
	DataType_Integer   DataType = 4
)

var DataType_name = map[int32]string{
	0: "Unknown",
	1: "Boolean",
	2: "Character",
	3: "Float",
	4: "Integer",
}

var DataType_value = map[string]int32{
	"Unknown":   0,
	"Boolean":   1,
	"Character": 2,
	"Float":     3,
	"Integer":   4,
}

func (x DataType) String() string {
	return proto.EnumName(DataType_name, int32(x))
}

func (DataType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{0}
}

type DatabaseMetadata struct {
	Version              uint32   `protobuf:"varint,1,opt,name=Version,proto3" json:"Version,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Opens                uint32   `protobuf:"varint,3,opt,name=Opens,proto3" json:"Opens,omitempty"`
	NextTableID          uint32   `protobuf:"varint,4,opt,name=NextTableID,proto3" json:"NextTableID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DatabaseMetadata) Reset()         { *m = DatabaseMetadata{} }
func (m *DatabaseMetadata) String() string { return proto.CompactTextString(m) }
func (*DatabaseMetadata) ProtoMessage()    {}
func (*DatabaseMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{0}
}

func (m *DatabaseMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatabaseMetadata.Unmarshal(m, b)
}
func (m *DatabaseMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatabaseMetadata.Marshal(b, m, deterministic)
}
func (m *DatabaseMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatabaseMetadata.Merge(m, src)
}
func (m *DatabaseMetadata) XXX_Size() int {
	return xxx_messageInfo_DatabaseMetadata.Size(m)
}
func (m *DatabaseMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_DatabaseMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_DatabaseMetadata proto.InternalMessageInfo

func (m *DatabaseMetadata) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *DatabaseMetadata) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DatabaseMetadata) GetOpens() uint32 {
	if m != nil {
		return m.Opens
	}
	return 0
}

func (m *DatabaseMetadata) GetNextTableID() uint32 {
	if m != nil {
		return m.NextTableID
	}
	return 0
}

type TableMetadata struct {
	ID                   uint32            `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Columns              []*ColumnMetadata `protobuf:"bytes,2,rep,name=Columns,proto3" json:"Columns,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TableMetadata) Reset()         { *m = TableMetadata{} }
func (m *TableMetadata) String() string { return proto.CompactTextString(m) }
func (*TableMetadata) ProtoMessage()    {}
func (*TableMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{1}
}

func (m *TableMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TableMetadata.Unmarshal(m, b)
}
func (m *TableMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TableMetadata.Marshal(b, m, deterministic)
}
func (m *TableMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TableMetadata.Merge(m, src)
}
func (m *TableMetadata) XXX_Size() int {
	return xxx_messageInfo_TableMetadata.Size(m)
}
func (m *TableMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_TableMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_TableMetadata proto.InternalMessageInfo

func (m *TableMetadata) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *TableMetadata) GetColumns() []*ColumnMetadata {
	if m != nil {
		return m.Columns
	}
	return nil
}

type ColumnMetadata struct {
	Name  string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Index uint32   `protobuf:"varint,2,opt,name=Index,proto3" json:"Index,omitempty"`
	Type  DataType `protobuf:"varint,3,opt,name=Type,proto3,enum=DataType" json:"Type,omitempty"`
	// Size of the column in bytes for integers and in characters for character columns
	Size                 uint32   `protobuf:"varint,4,opt,name=Size,proto3" json:"Size,omitempty"`
	Fixed                bool     `protobuf:"varint,5,opt,name=Fixed,proto3" json:"Fixed,omitempty"`
	Binary               bool     `protobuf:"varint,6,opt,name=Binary,proto3" json:"Binary,omitempty"`
	NotNull              bool     `protobuf:"varint,7,opt,name=NotNull,proto3" json:"NotNull,omitempty"`
	Default              string   `protobuf:"bytes,8,opt,name=Default,proto3" json:"Default,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ColumnMetadata) Reset()         { *m = ColumnMetadata{} }
func (m *ColumnMetadata) String() string { return proto.CompactTextString(m) }
func (*ColumnMetadata) ProtoMessage()    {}
func (*ColumnMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{2}
}

func (m *ColumnMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ColumnMetadata.Unmarshal(m, b)
}
func (m *ColumnMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ColumnMetadata.Marshal(b, m, deterministic)
}
func (m *ColumnMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ColumnMetadata.Merge(m, src)
}
func (m *ColumnMetadata) XXX_Size() int {
	return xxx_messageInfo_ColumnMetadata.Size(m)
}
func (m *ColumnMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_ColumnMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_ColumnMetadata proto.InternalMessageInfo

func (m *ColumnMetadata) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ColumnMetadata) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *ColumnMetadata) GetType() DataType {
	if m != nil {
		return m.Type
	}
	return DataType_Unknown
}

func (m *ColumnMetadata) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ColumnMetadata) GetFixed() bool {
	if m != nil {
		return m.Fixed
	}
	return false
}

func (m *ColumnMetadata) GetBinary() bool {
	if m != nil {
		return m.Binary
	}
	return false
}

func (m *ColumnMetadata) GetNotNull() bool {
	if m != nil {
		return m.NotNull
	}
	return false
}

func (m *ColumnMetadata) GetDefault() string {
	if m != nil {
		return m.Default
	}
	return ""
}

func init() {
	proto.RegisterEnum("DataType", DataType_name, DataType_value)
	proto.RegisterType((*DatabaseMetadata)(nil), "DatabaseMetadata")
	proto.RegisterType((*TableMetadata)(nil), "TableMetadata")
	proto.RegisterType((*ColumnMetadata)(nil), "ColumnMetadata")
}

func init() { proto.RegisterFile("metadata.proto", fileDescriptor_56d9f74966f40d04) }

var fileDescriptor_56d9f74966f40d04 = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0xc1, 0x4e, 0x83, 0x40,
	0x10, 0x86, 0x85, 0xd2, 0x02, 0xd3, 0x80, 0x64, 0x63, 0xcc, 0x5e, 0x4c, 0x48, 0x4f, 0xe8, 0xa1,
	0x87, 0xfa, 0x06, 0x2d, 0x69, 0x82, 0x46, 0x4c, 0xb0, 0x7a, 0xf0, 0xb6, 0x2d, 0x63, 0x25, 0xd2,
	0xdd, 0x06, 0xb6, 0x91, 0xfa, 0x92, 0xbe, 0x92, 0xd9, 0x05, 0x1a, 0x7b, 0x9b, 0xef, 0xff, 0x87,
	0x99, 0x9f, 0x59, 0xf0, 0x77, 0x28, 0x59, 0xce, 0x24, 0x9b, 0xee, 0x2b, 0x21, 0xc5, 0xa4, 0x81,
	0x20, 0x66, 0x92, 0xad, 0x59, 0x8d, 0x4f, 0x9d, 0x43, 0x28, 0xd8, 0x6f, 0x58, 0xd5, 0x85, 0xe0,
	0xd4, 0x08, 0x8d, 0xc8, 0xcb, 0x7a, 0x24, 0x04, 0xac, 0x94, 0xed, 0x90, 0x9a, 0xa1, 0x11, 0xb9,
	0x99, 0xae, 0xc9, 0x15, 0x0c, 0x9f, 0xf7, 0xc8, 0x6b, 0x3a, 0xd0, 0xbd, 0x2d, 0x90, 0x10, 0xc6,
	0x29, 0x36, 0x72, 0xc5, 0xd6, 0x25, 0x26, 0x31, 0xb5, 0xb4, 0xf7, 0x5f, 0x9a, 0x3c, 0x80, 0xa7,
	0xcb, 0xd3, 0x5a, 0x1f, 0xcc, 0x24, 0xee, 0x36, 0x9a, 0x49, 0x4c, 0x6e, 0xc1, 0x5e, 0x88, 0xf2,
	0xb0, 0xe3, 0x35, 0x35, 0xc3, 0x41, 0x34, 0x9e, 0x5d, 0x4e, 0x5b, 0xee, 0xbf, 0xc8, 0x7a, 0x7f,
	0xf2, 0x6b, 0x80, 0x7f, 0xee, 0x9d, 0xa2, 0x1a, 0xe7, 0x51, 0x13, 0x9e, 0x63, 0xa3, 0xf3, 0x7b,
	0x59, 0x0b, 0xe4, 0x06, 0xac, 0xd5, 0x71, 0x8f, 0x3a, 0xbf, 0x3f, 0x73, 0xa7, 0xea, 0x1e, 0x4a,
	0xc8, 0xb4, 0xac, 0x06, 0xbd, 0x14, 0x3f, 0xd8, 0xfd, 0x82, 0xae, 0xd5, 0xa0, 0x65, 0xd1, 0x60,
	0x4e, 0x87, 0xa1, 0x11, 0x39, 0x59, 0x0b, 0xe4, 0x1a, 0x46, 0xf3, 0x82, 0xb3, 0xea, 0x48, 0x47,
	0x5a, 0xee, 0x48, 0xdd, 0x33, 0x15, 0x32, 0x3d, 0x94, 0x25, 0xb5, 0xb5, 0xd1, 0xa3, 0x72, 0x62,
	0xfc, 0x60, 0x87, 0x52, 0x52, 0x47, 0xe7, 0xec, 0xf1, 0xee, 0x11, 0x9c, 0x3e, 0x07, 0x19, 0x83,
	0xfd, 0xca, 0xbf, 0xb8, 0xf8, 0xe6, 0xc1, 0x85, 0x82, 0xb9, 0x10, 0x25, 0x32, 0x1e, 0x18, 0xc4,
	0x03, 0x77, 0xf1, 0xc9, 0x2a, 0xb6, 0x91, 0x58, 0x05, 0x26, 0x71, 0x61, 0xb8, 0x2c, 0x05, 0x93,
	0xc1, 0x40, 0xb5, 0x25, 0x5c, 0xe2, 0x16, 0xab, 0xc0, 0x9a, 0xc3, 0xbb, 0x83, 0x7c, 0x23, 0xf2,
	0x82, 0x6f, 0xd7, 0x23, 0xfd, 0xee, 0xf7, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe4, 0xa4, 0x6b,
	0x80, 0x09, 0x02, 0x00, 0x00,
}
